(function (lib, img, cjs, ss) {

var p; // shortcut to reference prototypes
lib.webFontTxtFilters = {}; 

// library properties:
lib.properties = {
	width: 1920,
	height: 1080,
	fps: 24,
	color: "#FFFFFF",
	webfonts: {},
	manifest: []
};



lib.webfontAvailable = function(family) { 
	lib.properties.webfonts[family] = true;
	var txtFilters = lib.webFontTxtFilters && lib.webFontTxtFilters[family] || [];
	for(var f = 0; f < txtFilters.length; ++f) {
		txtFilters[f].updateCache();
	}
};
// symbols:



(lib.screen = function() {
	this.spriteSheet = ss["TextTest_atlas_"];
	this.gotoAndStop(0);
}).prototype = p = new cjs.Sprite();



(lib.test_v004_back = function() {
	this.spriteSheet = ss["TextTest_atlas_"];
	this.gotoAndStop(1);
}).prototype = p = new cjs.Sprite();



(lib.test_v004_front_a = function() {
	this.spriteSheet = ss["TextTest_atlas_"];
	this.gotoAndStop(2);
}).prototype = p = new cjs.Sprite();



(lib.timessquare001 = function() {
	this.spriteSheet = ss["TextTest_atlas_"];
	this.gotoAndStop(3);
}).prototype = p = new cjs.Sprite();



(lib.トゥイーン2 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// レイヤー 1
	this.instance = new lib.test_v004_front_a();
	this.instance.setTransform(-960,-540);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-960,-540,1920,1080);


(lib.トゥイーン1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// レイヤー 1
	this.instance = new lib.test_v004_front_a();
	this.instance.setTransform(-960,-540);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-960,-540,1920,1080);


(lib.Text = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// レイヤー 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#000000").s().p("AgnCCQASgKAMgRQAJgRAHgbQAFgaAAgdQAAgdgFgaQgDgUgEgMQgFgNgKgLQgJgLgPgKIAAgHQAWALAPAPQATAWALAdQAMAcAAAeQAAAtgWAlQgVAmgkAQg");
	this.shape.setTransform(402.1,515);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#000000").s().p("AgoB+QgCgEACgIQAGgTgHghQAAgIAFAGQAPAcAAAaQAAAQgNAAQgDAAgDgEgAAhB0QgEgdgRgYQgCgGAGADQAjAhAAAWQAAANgJAAQgHAAgCgMgAh/BzQAAgHAHgGQAVgPACghQAEgHACAIQACAngMARQgJAMgJAAQgIAAAAgIgABvBwQgSgfgXgRQgFgEAGAAQA5AYAAAaQAAALgJAAQgFAAgDgJgAhMAxIAAheIASALIAmAAIAAhfIAUADQAIAGgMACIAAAgIBRAAIAPgPIATAOQAHAGgHACIhzAAIAAAtIBCAAIAHgKIAQAMQAHAGgMACIAABCQgPAOAAgNIAAgHIh+AAIAAAMQgIAHgDAAQgEAAAAgGgAg9AdIB+AAIAAg4Ih+AAg");
	this.shape_1.setTransform(382.5,511.1);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#000000").s().p("AAtB9QACgHgJgCIgUgEQAAAAgBgBQAAAAAAgBQAAAAAAgBQABgBAAAAIAdAAQALAAABgIIAAhJIhoAAIAAgHIBoAAIAAgqIhpAAIAAgHIBAAAIAAgrIg4AAIAAgHIA4AAIAAgzIAVADQANAFgSAEIAAAnIArAAIAPgPIASAOQAIAGgIACIhMAAIAAArIA9AAIAOgPIATAOQAIAGgIACIg2AAIAAAqIAVAAIAMgNIARAMQAGAGgGACIgyAAIAABOQAAAQgNAHQgGADgEAAQgFAAgBgGgAiDBYIAAjBIARAKIAlAAIAIgLIATANQAJAHgSACIAACdQgPAOABgNIAAgSIgrAAIAAAfQgIAHgEAAQgDAAAAgGgAh0AxIArAAIAAg/IgrAAgAh0gWIArAAIAAhCIgrAAgAgFBGQgDgLgRgPQgEgEAHABQAjAOAAATQAAAOgJAAQgEAAgFgSg");
	this.shape_2.setTransform(353.4,511.1);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#000000").s().p("AgSBlIA5ixIg1AAQgQAAgHAEQgMAHgIAOIgEgCIATgvIBoAAIAAAGIhADDg");
	this.shape_3.setTransform(329.8,512.5);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#000000").s().p("AgiBlIAAgGQAOAAAEgCQAEgCACgEQABgDAAgSIAAhpQAAgWgBgGQgBgFgDgCQgCgCgEAAQgGAAgJAEIgDgEIAvgYIAFAAIAACmQAAAQABAFQABAEAFACQAEACAOAAIAAAGg");
	this.shape_4.setTransform(314.8,512.1);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#000000").s().p("AgKBCQgFgFAAgGQAAgHAFgFQAFgFAFAAQAGAAAFAFQAFAFAAAHQAAAGgFAFQgFAFgGAAQgFAAgFgFgAgKgqQgFgFAAgGQAAgHAFgFQAFgFAFAAQAGAAAFAFQAFAFAAAHQAAAGgFAFQgFAFgGAAQgFAAgFgFg");
	this.shape_5.setTransform(303.3,515.5);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#000000").s().p("AgvBhQgIgEAAgGQAAgFADgDQAEgDAFAAIAHACIALAEQAKAFADABQAFACAGAAQANAAAMgMQALgLgBgQQAAgMgEgLQgFgIgEgEQgHgGgKgEQgJgGgMAAIgEAAIAAgCQALgCAKgGQAMgHAEgKQAGgJAAgMQAAgPgJgKQgKgJgMAAQgXAAgPAZIgFgDQAIgUAOgKQAMgMASABQAYAAAMAPQAKALAAANQAAAWgbAXQATAIAIALQAKANAAASQAAAagQATQgWAZgmAAQgVgBgGgFg");
	this.shape_6.setTransform(290.9,512.3);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#000000").s().p("AhABlIAAgGQAzgvATgeQAWgcAAgYQAAgTgMgMQgMgNgOAAQgOAAgMAJQgMAJgFAQIgFAAQAEgbAPgOQAOgPAXAAQAXAAAQAQQAQAPAAAVQAAAPgHAPQgLAWgYAbIgsAwIAyAAQAQAAAHgCQAFgBAFgDQAGgEADgGIAGAAIgOAmg");
	this.shape_7.setTransform(276.3,512.1);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#000000").s().p("AgrBVQgNgPAAgRQAAgNAJgNQAJgNAWgOQgYgTgHgLQgGgMAAgMQAAgUAPgOQAOgOAYABQAXgBAPANQAPAOAAAQQAAALgIAMQgIALgZAQQAZASAJAMQALAOAAARQAAAVgQAOQgQAQgZAAQgbgBgQgRgAgbAbQgGAMAAAOQAAATAKAMQAKAKAOABQAQgBAKgIQAJgKAAgMQAAgLgFgIQgLgPgdgZQgMAKgGAMgAgXhUQgJAIAAAMQAAAHAEAIQAEAIAHAGIAWAUQARgQAFgIQAFgKAAgMQAAgPgJgIQgJgJgOAAQgNAAgKAJg");
	this.shape_8.setTransform(254.1,512.3);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#000000").s().p("AgiBlIAAgGQAOAAAEgCQAEgCACgEQABgDAAgSIAAhpQAAgWgBgGQgBgFgDgCQgCgCgEAAQgGAAgJAEIgDgEIAvgYIAFAAIAACmQAAAQABAFQABAEAFACQAEACAOAAIAAAGg");
	this.shape_9.setTransform(239,512.1);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#000000").s().p("AgoBqIBGjTIALAAIhGDTg");
	this.shape_10.setTransform(227.4,512);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#000000").s().p("AgwBhQgHgEAAgGQAAgFAEgDQADgDAFAAIAHACIAMAEQAIAFAEABQAFACAGAAQANAAALgMQALgLAAgQQAAgMgEgLQgFgIgEgEQgGgGgLgEQgJgGgMAAIgEAAIAAgCQALgCAKgGQAMgHAEgKQAGgJAAgMQAAgPgJgKQgKgJgMAAQgXAAgPAZIgFgDQAJgUANgKQANgMARABQAYAAANAPQAJALABANQAAAWgcAXQASAIAKALQAJANAAASQAAAagQATQgWAZgnAAQgTgBgIgFg");
	this.shape_11.setTransform(215.1,512.3);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#000000").s().p("AgoBqIBGjTIALAAIhGDTg");
	this.shape_12.setTransform(204.1,512);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#000000").s().p("AgwBfQgIgGAAgIQAAgEADgDQADgEAFAAQAEAAADACIAKAGQALAHALAAQAPABANgNQANgNAAgTQAAgSgLgQQgMgNgSgJQgQgGgcgBIAmhOIBFAAIgLAZIg6AAIgNAbQAlAGAXAXQATATAAAZQAAARgGANQgGANgKAJQgKAJgMAHQgPAHgRABQgSgBgIgFg");
	this.shape_13.setTransform(192.1,512.5);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#000000").s().p("AgiBlIAAgGQAOAAAEgCQAEgCACgEQABgDAAgSIAAhpQAAgWgBgGQgBgFgDgCQgCgCgEAAQgGAAgJAEIgDgEIAvgYIAFAAIAACmQAAAQABAFQABAEAFACQAEACAOAAIAAAGg");
	this.shape_14.setTransform(177.3,512.1);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#000000").s().p("AgvBFQgQgdAAgnQAAggAKgYQALgZARgMQANgJAMAAQAXAAASAWQAXAdAAAyQAAAggKAZQgKAXgQALQgPAMgNAAQgcAAgTgigAgQhTQgLAMgDAaQgEAaAAAYQAAAoAKAaQAIAXAQAAQAHgBAIgGQAJgIAEgRQAHgZAAgsQAAghgHgYQgFgQgJgHQgGgFgIAAQgIAAgIAJg");
	this.shape_15.setTransform(162.4,512.3);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#000000").s().p("AhABlIAAgGQAzgvAUgeQAVgcAAgYQAAgTgLgMQgMgNgOAAQgPAAgLAJQgMAJgGAQIgGAAQAFgbAOgOQAPgPAYAAQAVAAARAQQAQAPAAAVQAAAPgHAPQgLAWgZAbIgrAwIAyAAQAQAAAGgCQAGgBAGgDQAFgEAEgGIAFAAIgOAmg");
	this.shape_16.setTransform(147.1,512.1);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#000000").s().p("AADBuQgTgVgMgdQgLgdAAgfQAAgsAWglQAVglAkgRIAAAHQgSAKgMARQgKARgFAbQgGAaAAAdQAAAdAFAaQAEAUADANQAGAMAJALQAJALAPAKIAAAGQgWgLgPgPg");
	this.shape_17.setTransform(135.1,515);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#000000").s().p("AgzB8QgHgDAHgEQBTgCAfgfQAMgNAAgVQAAgSgJgKQgTgTgcAAQgmAAgcAdQgRARgEARQgCAKgIgFQgNgHABgWQABgdAFgWQACgNAAgMQAAgJgDgFQgEgGAFgHQAJgOAWgFQALgCASAAQAAAAAAAAQABgBAAAAQAAAAAAgBQAAAAAAgBQgBgDgIgBQgZgFgNgbQAAgBAAgBQAAAAABAAQAAAAABAAQAAAAABABQAOARAkAHQAUAFACATQABAKgIgEQgPgHgLAAQghAAgNAMQgIAJAIAIQAHAHgDAMQgHAXABAsQAAAHAFgHQApgqAvAAQAoAAAUASQAPAQAAAVQAAAXgRARQghAfhYAAIgFAAg");
	this.shape_18.setTransform(320.8,475.8);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#000000").s().p("Ah/BrIgBgJQAAgLAHgHQAHgGAJgUQAagyAUgsQgjAIgKAEQgHADgFgEQgMgIAAgQQAAgBABgBQAAAAAAAAQABAAAAAAQABABAAABQAGAMANAAQAIAAAqgGIAMgbQAGgRgHgIQgGgIgNAAQgEgDAEgCIARABQANAEAJAJQAKALgLACQgIATgKARIAWgCQAQAAAGAIQAJANAAAeQAABZgpAWQgMAFAAgKQAAgIgEgDIgYgSQgCgFAEABIAbAPQAMAFAJgNQALgPAFgWQAGgcAAgWQAAgVgEgHQgFgJgNAAQgMAAgNACIg3B6QgEAGgHASQgDAJgFAAQgEAAgCgGgABvArQgHgMgKACIgiACQgHgCAFgDIAogGQAJgBgCgGQgCgRgPgTQgOgUgXgMQgFgFAIACQAUAHAWASQAdAXAEAgQABAMgFAGQgDAFgDAAQgEAAgEgGg");
	this.shape_19.setTransform(294.9,476.1);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#000000").s().p("AgSBlIA5ixIg1AAQgQAAgHAEQgMAHgIAOIgEgCIATgvIBoAAIAAAGIhADDg");
	this.shape_20.setTransform(272.9,477.3);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#000000").s().p("AgrBVQgNgPAAgQQAAgNAJgNQAJgNAWgPQgYgTgHgLQgGgMAAgNQAAgTAPgNQAOgOAYgBQAXABAPANQAPAMAAARQAAALgIALQgIANgZAPQAZASAJAMQALAPAAAQQAAAVgQAOQgQAPgZABQgbgBgQgRgAgbAbQgGAMAAAOQAAATAKAMQAKALAOgBQAQABAKgKQAJgJAAgMQAAgLgFgIQgLgPgdgaQgMALgGAMgAgXhVQgJAJAAALQAAAIAEAIQAEAHAHAIIAWAUQARgQAFgKQAFgJAAgLQAAgQgJgJQgJgIgOAAQgNAAgKAIg");
	this.shape_21.setTransform(258,477.1);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#000000").s().p("AgSBlIA5ixIg1AAQgQAAgHAEQgMAHgIAOIgEgCIATgvIBoAAIAAAGIhADDg");
	this.shape_22.setTransform(242.9,477.3);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f("#000000").s().p("AgpBqIAAgHIASAAQAJAAAEgEQAFgFAAgIIAAg5IhVAAIAAgHIBVAAIgZgiIg8AAIAAgHIA5AAIgthAQgCgEgHgDQgHgEgHAAIgJAAIAAgHIBXAAIAAAHIgOAAQgVAAAMATIAkA4IAqAAIAhg5QADgHgGgGQgEgFgIAAIgMAAIAAgHIBJAAIAAAHIgEAAQgVAAgKAPIgjA8IA8AAIAAAHIg/AAIgYAiIBXAAIAAAHIhWAAIAAA5QAAAIAFAFQAFAEAIAAIATAAIAAAHgAAJAIIADAAIAQgYIgiAAg");
	this.shape_23.setTransform(220.3,476.3);

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.f("#000000").s().p("AhcB/IAAh/QgQAhgbAbQgHAFADgJQAmg4AJg8IgpAAIAAgHIApAAIAAhBIAUADQAKAGgOACIAAA2IARAAIAPgPIATAOQAHAGgHACIgzAAIAAAmQAdAHAIAIQAGAGAAAHQAAAHgFAAQgEAAgHgKQgKgMgRgHIAACOQgIAHgEAAQgEAAAAgGgAgNB+IAAhhQgUAOgaALQgJACAHgIQA2geAjgnQgTgWgHgbQgNAagdAXQgGAEABgGQAqgsAQg/IAVAHQAJAHgRACQgGANgHAMIBAAAIAHgJIASANQAHAFgQACQgUAfgaAbQAoAeA2AKQgNAEgIANQgrgOgnghQgYAUgUAOIAIAKIBIAAIAHgJIAQAMQAHAGgLACIAABLQgQAOAAgNIAAgMIhNAAIAAAQQgGAHgEAAQgDAAAAgGgAAABmIBNAAIAAg9IhNAAgAAHhMQAIAZAVAVQAXgXAQgdIhCAAg");
	this.shape_24.setTransform(313.8,440.9);

	this.shape_25 = new cjs.Shape();
	this.shape_25.graphics.f("#000000").s().p("AgvCCIAAinIARAKIAfAAIAAhFIg0AAIAAgHICZAAIAPgPIATAOQAHAGgHACIhGAAIAABFIAlAAIAHgJIAQAMQAIAGgMACIAACKQgPAPAAgNIAAgQIiLAAIAAAUQgIAHgEAAQgDAAAAgFgABCBlIApAAIAAh5IgpAAgAAQBlIAiAAIAAh5IgiAAgAggBlIAhAAIAAh5IghAAgAAQgbIAiAAIAAhFIgiAAgAheCAIAAieQgTAcgUATQgIAFAFgIQAvhEAVhQIAYAJQAIAFgUAEQgMAggOAcIAJAFQAJAGgJACIgGABIAACpQgIAHgEAAQgDAAAAgGg");
	this.shape_25.setTransform(283.4,441);

	this.shape_26 = new cjs.Shape();
	this.shape_26.graphics.f("#000000").s().p("AANB3IAAh0IARAKIBAAAIAHgIIAPAKQAHAGgMACIAABZQgPAPAAgNIAAgMIhEAAIAAAQQgIAIgEAAQgDAAAAgHgAAcBfIBEAAIAAhLIhEAAgAh2B3IAAh1IASALIA8AAIAHgIIAPAKQAHAGgMACIAABWQgPAOAAgNIAAgIIhBAAIAAAQQgHAIgEAAQgEAAAAgHgAhnBfIBBAAIAAhLIhBAAgAhBgNIAAhwIASAMIBVAAIAHgIIAQAKQAHAGgMADIAABMQgPAOAAgNIAAgLIhbAAIAAAWQgIAHgDAAQgEAAAAgGgAgygrIBbAAIAAg/IhbAAg");
	this.shape_26.setTransform(254,440.9);

	this.shape_27 = new cjs.Shape();
	this.shape_27.graphics.f("#000000").s().p("ABQCCIAAiYIgpAAIAAAZQAABVhFAmQgIACAFgIQA5glAAhMIAAh2IASAMQAsgMAWgKIATANQAGAHgSgDQgeAGguAGIAAA/IBAAAIAPgPIATAOQAHAGgHACIgpAAIAACXQgIAHgEAAQgEAAAAgGgAhEB+IAAhRQgZAngrAdQgEACABgFQAlgiAhg4Ig4AAIAAgHIA5AAIAAglIg/AAIAAgHIBXAAIAOgwIAQAGQAPAHgSADIgVAgIAXAAIANgNIAOAMQAHAGgHACIhAAAIAAAlIAkAAIANgNIAOALQAHAGgHADIg/AAIAAARQAfAHANAKQAIAGAAAIQAAAHgGAAQgEAAgGgHQgPgTgVgGIAABSQgIAIgEAAQgEAAAAgHgAhcguQgDgVgHgJQgDgEAGABQAWAQAAAOQAAANgIAAQgGAAgBgKgAh+hWIAAgHIA6AAIAAgqIAUADQAKAGgOACIAAAfIAaAAIAQgPIAQAOQAHAGgHACg");
	this.shape_27.setTransform(223.8,440.8);

	this.shape_28 = new cjs.Shape();
	this.shape_28.graphics.f("#000000").s().p("AgnCCQASgKAMgRQAJgRAHgbQAFgaAAgdQAAgdgFgaQgEgUgDgMQgFgNgKgLQgJgLgPgKIAAgHQAWALAPAPQATAWALAdQAMAcAAAeQAAAtgWAlQgVAmgkAQg");
	this.shape_28.setTransform(529.9,409.3);

	this.shape_29 = new cjs.Shape();
	this.shape_29.graphics.f("#000000").s().p("AgwBuQgDgIAEgPQAEgogBiJQAAgMgEgGQgDgFgNgBQgFgCAFgDQAIgCAOAEQAJADAHAFQAHAEAAAFQAAAEgEABQgFABAAAFQgDAeABAiQAOABAVAGQAcAIARALQARAOAAAKQAAAKgIAAQgFAAgIgKQgXgdg1gQIAACAQAAANgGAAQgHAAgFgLg");
	this.shape_29.setTransform(516.8,405.8);

	this.shape_30 = new cjs.Shape();
	this.shape_30.graphics.f("#000000").s().p("AhOBPQBugtAihkQADgHgMgGQgFgCAHgBQALABAHAFQAQALAAAGQAAADgGAAQgGAAgDAIQgvBihrAjQgHAAAFgGgAg9gVQgEgNgEgFQgHgKgPgLQgBAAAAgBQAAAAAAgBQAAAAABAAQAAgBABAAQAJACAMAIQAJAFAGAGQAKAJgBAIQgCAKgFAAQgGAAgDgGgAgJgrQgHgQgGgIQgGgGgNgHQgDgEAEAAQAOACAPAKQAPAMAAAPQAAAHgFABQgGAAgCgGg");
	this.shape_30.setTransform(496.5,410.3);

	this.shape_31 = new cjs.Shape();
	this.shape_31.graphics.f("#000000").s().p("AhMBUIgNgPQAEgCACgFIAAh+QAAgLgEgFQgEgGgMgBQgFgCAFgDQAQgBAOAGQAPAGAAAEQAAADgGAEQgFAEAAAFIAAB/QBVgkBWhJQAFgBgBAFQg2A8hwA9QgDALgEAAQgCAAgHgJg");
	this.shape_31.setTransform(473.2,405.7);

	this.shape_32 = new cjs.Shape();
	this.shape_32.graphics.f("#000000").s().p("AhqB2QBtgnAth/QADgHgGAAQgaAChpANQgEACgGAEQgBAEgEAAQgDAAgMgLQgKgIgBgJQAAgGAFAEQAFAJAPAAICJgLQAOgCAEgIQAOAHAJAJQAGAGAAADQAAAEgIAAQgIAAgBAFQg0CAh0AiQgHAAAEgGgABRhLQgFgHgSgPQgBgBAAAAQAAgBAAAAQAAgBAAAAQABAAABgBQAQAFASAMQAKAHAAAKQAAAJgHAAQgEAAgLgRgABzhaQgFgFgEgHQgJgJgOgIQgDgEAFAAQAbAFAJAJQAHAHAAAIQAAAGgGAAQgFAAgCgCg");
	this.shape_32.setTransform(446.4,404.3);

	this.shape_33 = new cjs.Shape();
	this.shape_33.graphics.f("#000000").s().p("Ag/ByQBpgqgBhWIAAhSQgBgJgEgFQgDgFgMgBQgBgBAAAAQAAgBAAAAQAAAAABgBQAAAAABAAQATgDAPAHQALAFAAADQAAAGgLAGIAABRQABBgh2AnQgIgCAGgFgAgqAUQgEgHABgDIACgSIAAhPQAAgIgEgEQgFgFgJgBQgFgDAFgCQASgBANAHQAKADAAAFQAAAEgEABQgDABAAAJIAABYQABATgJAAQgDAAgEgGg");
	this.shape_33.setTransform(422.4,406);

	this.shape_34 = new cjs.Shape();
	this.shape_34.graphics.f("#000000").s().p("AgKBSQgmAohPAJQgHAAAEgFQBOgPAegmQgYgYgTgaIAIgEQAOAVAcAWQAMgTABglIhOAAIAAARQgQAOAAgOIAAhsIASAKIBMAAIAAg4IATADQANAFgTAEIAAAsIBEAAIAIgKIATAMQAKAHgSACIAABQQgPAOAAgMIAAgMIhIAAQAAAsgNAUQA4ApBOAAQgQAKgDALQhFgHg2grgAALAAIBIAAIAAhEIhIAAgAhQAAIBOAAIAAhEIhOAAg");
	this.shape_34.setTransform(399.1,405.3);

	this.shape_35 = new cjs.Shape();
	this.shape_35.graphics.f("#000000").s().p("AhyCAQBIgbAAgwIAAgsQgoAqgwAUQgKABAHgHQBBgiApg8IgqAAIAAAUQgPAMAAgLIAAh8IASAMICEAAIAHgJIARAMQAHAFgMADIAABeQgPAPAAgNIAAgQIg2AAQAwAyBJANQgOAGgHANQgmgQgbgUIgHADIAABpQgPAOAAgNIAAh4IAOADQgWgSgOgUIgOAAQgQAXgPAMIAQACQAKAGgPADIAAAjQAAA6hWAXQgGgBAFgEgAAHgkIA/AAIAAgiIg/AAgAhFgkIA+AAIAAgiIg+AAgAAHhNIA/AAIAAgkIg/AAgAhFhNIA+AAIAAgkIg+AAg");
	this.shape_35.setTransform(369.1,405.9);

	this.shape_36 = new cjs.Shape();
	this.shape_36.graphics.f("#000000").s().p("AhTB8IAAiiIg1AAIAAgHIA1AAIAAhNIAUAEQAJAGgNACIAABBIA3AAIAAhUIARAEQAKAGgOACIAABIIAyAAIAAhSIAUADQAKAGgOACIAABHIAbAAIARgSIAWAQQAHAGgHADIhCAAIAABfQgQAOAAgNIAAgSIgyAAIAAAbQgOAOABgMIAAhrIg3AAIAACHICZAAIASgSIAWARQAHAFgHADIjBAAIAAATQgJAHgDAAQgEAAAAgGgAABAhIAyAAIAAhHIgyAAg");
	this.shape_36.setTransform(339.3,406.1);

	this.shape_37 = new cjs.Shape();
	this.shape_37.graphics.f("#000000").s().p("AADBuQgTgVgMgdQgLgdAAgfQAAgsAWglQAVglAkgRIAAAHQgSAKgMARQgKARgFAbQgGAaAAAdQAAAdAFAaQAEAUADANQAGAMAJALQAJALAPAKIAAAGQgWgLgPgPg");
	this.shape_37.setTransform(319.2,409.3);

	this.shape_38 = new cjs.Shape();
	this.shape_38.graphics.f("#000000").s().p("AiFB4QA+gjAZguQAcgzADhJIAAgnIAWADQANAFgTAFIAAAPQAPCWB4AuQgRAAgQAOQhZg4gQiHQgDBPgeAvQgdAuhDAeIgBAAQgFAAAEgFg");
	this.shape_38.setTransform(291.6,406.3);

	this.shape_39 = new cjs.Shape();
	this.shape_39.graphics.f("#000000").s().p("AAIB+QAsgjASgeQgNgigBgwIhlAAIAAgHIA1AAIAQg2IAPAGQALAGgQACIgUAoIAqAAIAAhjIAVADQAMADgSAHIAABWIAbAAIAPgPIATAOQAHAGgHACIg9AAQABAqAIAYQANgZALgcIAQAIQANADgTAFQgMAcgQAZQAKASAIAJQAIAIAEAAQADAAABgGIAHghQAEgGACAHIgDAlQAAAJAGADQAEADAAADQAAAHgOAAQgOAAgPgPQgMgMgJgUQgaAigoAYIgCAAQgEAAAEgFgAh5B4IAAhrIARAJIAbAAIAHgJIARALQAHAGgMACIAABKQgPAOAAgNIAAgKIghAAIAAAWQgIAHgEAAQgDAAAAgGgAhqBaIAhAAIAAg9IghAAgAggBmIAAhqIARAHIAgAAIAHgHIARAJQAHAGgMADIAABMQgPAOAAgNIAAgFIgmAAIAAAOQgIAHgEAAQgDAAAAgFgAgRBPIAmAAIAAgfIgmAAgAgRApIAmAAIAAgfIgmAAgAiCgHIAAgHIAzAAIALgLIARANQADAEgFABgAgWgxQgBgRgJgQQgDgFAGADQAWAVAAATQAAAKgIAAQgIAAABgPgAiAgmIAAgHIAtAAIAMgMIAQANQAEAFgGABgABqhJQgHgNgOgKQgFgEAJABQAlANgCAPQgBAHgGAAQgGAAgFgJgAiLhGIAAgHIBDAAIAPgPIATAOQAHAGgHACgAgmhXIAAgHIAhAAIAAgkIARAEQAKADgOAFIAAAYIAMAAIAMgNIARALQAHAGgHADgAh/hmIAAgHIArAAIANgMIAQALQAHAGgHACg");
	this.shape_39.setTransform(261.3,405.8);

	this.shape_40 = new cjs.Shape();
	this.shape_40.graphics.f("#000000").s().p("AiBB9QBIgzAChFIhIAAIAAgFIBJAAIAAg5IgdAAQgPAXgMALQgEABABgEQAbgpAOg9IAYAJQAGAGgQADIgVAtIA+AAIANgMIAOALQAHAGgHADIgwAAIAAA5IAfAAIAOgQIASAOQAHAEgHADIhAAAQgCAVgHAUQAcAOAUAUQAKALAAAKQAAAMgGAAQgHAAgFgNQgIgYgigZQgWAzg3AbQgFAAADgEgAAjBvIAAi7IARAKIA1AAIAHgJIAQALQAIAGgMADIAACXQgPAOAAgNIAAgQIg7AAIAAAcQgIAHgEAAQgDAAAAgFgAAyBKIA7AAIAAiFIg7AAg");
	this.shape_40.setTransform(230.9,405.3);

	this.shape_41 = new cjs.Shape();
	this.shape_41.graphics.f("#000000").s().p("Ah5B9IAAkAIARAMIDEAAIAIgKIATAMQAKAHgSADIAADiQgPAOAAgMIAAgMIjKAAIAAAPQgIAIgEAAQgDAAAAgHgAhqBmIDKAAIAAjWIjKAAgAhVBAIAAgHIBDAAIAAhCIg1AAIAAgHIA1AAIAAg2IhBAAIAAgHIB+AAIANgNIAQAMQAHAGgHACIhLAAIAAA2IAlAAIALgLIARAMQADAFgGABIg+AAIAABCIA2AAIAPgPIATAOQAHAGgHACgAAiAkQgLgRgNgJQgDgDAGAAQAjAJAAASQAAAJgGAAQgFAAgDgHg");
	this.shape_41.setTransform(202,406.3);

	this.shape_42 = new cjs.Shape();
	this.shape_42.graphics.f("#000000").s().p("AgNB+IAAhqIhSAAIAAANQgQAOAAgNIAAh5IASAKIBQAAIAAg3IATAEQANAEgTAFIAAAqIBSAAIAIgKIATANQAJAHgRACIAABfQgQAOAAgNIAAgLIhVAAIAABpQgGAIgEAAQgDAAAAgHgAAAANIBVAAIAAhTIhVAAgAhfANIBSAAIAAhTIhSAAg");
	this.shape_42.setTransform(172.1,405.9);

	this.shape_43 = new cjs.Shape();
	this.shape_43.graphics.f("#000000").s().p("AhFBlQgNgNAAgQQAAgTATgSQATgRAcgQQgOgOAAgeQAAg2gCgGQgFgMgMAAQgEgCAEgDQAUgCARANQAFAFgFAEQgDAEAAAKIAAA9QAAAUAGAEQAfgNAjgLQAKgCgHgJQgCgEgGgDQgFgDAGgBQAOABAIAKQAHAKABAHQgBAGgIAAQg0ALgjAPQghAPgQASQgLAMAAALQABAZAdAIQANAEAkAAQAjAAAOgFQAMgFAHAFQAEAEAAAEQAAAFgHABQgVAEg3AAQgtAAgTgTg");
	this.shape_43.setTransform(146.2,405.4);

	this.shape_44 = new cjs.Shape();
	this.shape_44.graphics.f("#000000").s().p("ABVB8QgEgIgKgOIieAQQgHAWgGgOIgLgWIA1gBIAYhDIhgAAIAAgHIDYAAIAPgPIATAOQAHAGgHACIiGAAIgjBCIBzgGQgPgQgTgOQgGgEAIABQAfAMAWASQAQAOAAAQQAAALgIAAQgGAAgEgKgAiFgLQBOgtAvhNIAXAKQAGAKgRgEQAsA6BXAfQgOAFgHAMQhNgoglg/QhCBUhBAXQgGAAAEgEgAhKgRIAAgHIBoAAIAMgNIARAMQAHAGgHACg");
	this.shape_44.setTransform(120.2,405.5);

	this.shape_45 = new cjs.Shape();
	this.shape_45.graphics.f("#000000").s().p("AhsBVQBwg8AxhdQACgEgGAAQhWAMgFAHQgCADgEAAQgCAAgIgHQgSgPACgIQAAgGAFAEQAGALAMAAQAcAABLgJIALgJQAJAGAIAHQAFAEAAAEQAAAEgLAAQgWAjgYAdQAnALAZAZQAUAUAAAMQAAAKgJAAQgFAAgHgMQgLgRgOgOQgQgRgagQQg5A7hHAdIgEAAQgFAAAFgFg");
	this.shape_45.setTransform(92.4,405.8);

	this.shape_46 = new cjs.Shape();
	this.shape_46.graphics.f("#000000").s().p("AiABrQByg8AvhdQACgEgGAAQhWAMgFAHQgCADgEAAQgCAAgIgHQgSgPACgIQAAgGAFAEQAGALAMAAQAcAABLgJIALgJQAJAGAIAHQAFAEAAAEQAAAEgLAAQgWAjgYAbQAnANAZAZQAUAUAAAMQAAAKgJAAQgFAAgHgMQgLgRgOgOQgQgRgagQQg5A7hHAdIgEAAQgFAAAFgFgABPhEQgFgHgSgPQgBgBAAAAQAAgBAAAAQAAAAAAgBQABAAABgBQAQAFASAMQAKAHAAAKQAAAJgHAAQgEAAgLgRgAB3hOIgJgMQgJgJgOgJQgDgDAEAAQAbAFAKAJQAHAHAAAIQAAAGgGAAQgFAAgCgCg");
	this.shape_46.setTransform(67.4,403.6);

	this.shape_47 = new cjs.Shape();
	this.shape_47.graphics.f("#000000").s().p("AhxA8QgJgHgEgKQAAgIAFAFQAIAJANAAQAcABBHgHIAAg+QAAgJgDgHQgDgHgLgGQgvAGgEADQgGADgEAAQgCAAgKgIQgKgKAAgHQABgHACAEQAHALAQgBIAXAAQA0gEA5gDIAQgGQAJADAHAGQAGAFAAADQAAAEgHgCQgggFg9AEIAQAKQAIAEAAAEQAAAEgHACIgDBCIBJgBQALAAAHgHQAIADAJAHQAKAHAAAFQAAAFgJgDQgUgFgSAAQhMgGhSAPQgKACgEACQgCAEgGgBQgDABgKgJg");
	this.shape_47.setTransform(39.5,406);

	this.shape_48 = new cjs.Shape();
	this.shape_48.graphics.f("#000000").s().p("AAYByQgHgIACgIQAEgNAAgIIAAhlQhDAyg5AWQgJAAAHgHQB3g/A6hLQAFgGgBgGQgBgDgKgFQgHgCAKgBQASABAKANQAJAIAAAEQAAAFgHgBQgGAAgGAFQgVAYghAaQAaAJgWAEIAACFQAAAKgFAAQgDABgGgIg");
	this.shape_48.setTransform(13.4,406);

	this.shape_49 = new cjs.Shape();
	this.shape_49.graphics.f("#000000").s().p("AgaAbQgKgLAAgQQAAgPAKgKQALgLAPAAQAQAAAKALQALAKAAAPQAAAQgLALQgKAKgQAAQgPAAgLgKgAgTgUQgJAJABALQgBAMAJAIQAHAJAMAAQANAAAHgJQAJgIAAgMQAAgLgJgJQgHgIgNAAQgMAAgHAIg");
	this.shape_49.setTransform(292.6,345.3);

	this.shape_50 = new cjs.Shape();
	this.shape_50.graphics.f("#000000").s().p("AgsB/QAOgLAKgLQAYgeABgpQgHAPgPAAQgNAAgLgLQgIgIAAgRQAAgOAMgMQAJgJAOAAQALAAAGAFIAAgnQg8AJgfAKIgQAFQgHAEgGgFQgNgJgGgSQAAgGAFAFQAGALAQAAQARAAAigGQAbgFAigDIAAggQAAgbgVgCQgFgDAFgCQASgCALAIQAGADAFAHQAEAGgFADQgEADAAAkIBGgFIAYgFQAGgBAFAEQANALACAEQACAHgJgDQgYgGgkAAQgXAAgeADIAAAyQAEAKAAAVQAABKg/AhIgCAAQgBAAAAAAQgBAAAAgBQAAAAABgBQAAgBABgBgAghgHQgFAHAAALQAAATAJAIQADADAJAAQAIAAAFgEQAIgLAAgTQAAgXgSAAQgNAAgGAJg");
	this.shape_50.setTransform(272.9,335.5);

	this.shape_51 = new cjs.Shape();
	this.shape_51.graphics.f("#000000").s().p("AABBUQgjgeAAgwQAAgqAsglQAGgEgGAAIhDAOQgOACgOAHQgLAFgDgBQgGgCgGgEQgNgKgBgKQACgIADAHQAFAKATgBQAKAAAWgFIB4gWQASgDAHgGQAHgGAJAGIAOAKQAGAGgJACQhIgCggAgQgcAeAAAdQAAAjAXAXQAXAZAfABQAMAAAEAFQAEAGAAAEQAAAGgJAAQghAAgegYgABQgLQgIgSgWgOQgDgEAEABQAUAEAPALQAHAGACAJQADAJgHACIgDABQgFAAgDgHgABvgdQgIgTgXgOQgCgEADACQAUADAQAMQAHAGACAIQACAJgHADIgCAAQgGAAgCgGg");
	this.shape_51.setTransform(244,335.7);

	this.shape_52 = new cjs.Shape();
	this.shape_52.graphics.f("#000000").s().p("Ag4CJIAAgzIA/AAIAAjeIAzAAIAAERgAguB+IBdAAIAAj7IgeAAIAADdIg/AAg");
	this.shape_52.setTransform(428.3,300.1);

	this.shape_53 = new cjs.Shape();
	this.shape_53.graphics.f("#000000").s().p("AiFB4QA+gjAZguQAcgzADhJIAAgnIAWADQANAFgTAFIAAAPQAPCWB4AuQgRAAgQAOQhZg4gQiHQgDBPgeAvQgdAuhDAeIgCAAQgEAAAEgFg");
	this.shape_53.setTransform(406,300.6);

	this.shape_54 = new cjs.Shape();
	this.shape_54.graphics.f("#000000").s().p("AAIB+QAsgjASgeQgNgigBgwIhlAAIAAgHIA1AAIAQg2IAPAGQALAGgQACIgUAoIAqAAIAAhjIAVADQAMADgSAHIAABWIAbAAIAPgPIATAOQAHAGgHACIg9AAQABAqAIAYQANgZALgcIAQAIQANADgTAFQgMAcgQAZQAKASAIAJQAIAIAEAAQADAAABgGIAHghQAEgGACAHIgDAlQAAAJAGADQAEADAAADQAAAHgOAAQgOAAgPgPQgMgMgJgUQgaAigoAYIgCAAQgEAAAEgFgAh5B4IAAhrIARAJIAbAAIAHgJIARALQAHAGgMACIAABKQgPAOAAgNIAAgKIghAAIAAAWQgIAHgEAAQgDAAAAgGgAhqBaIAhAAIAAg9IghAAgAggBmIAAhqIARAHIAgAAIAHgHIARAJQAHAGgMADIAABMQgPAOAAgNIAAgFIgmAAIAAAOQgIAHgEAAQgDAAAAgFgAgRBPIAmAAIAAgfIgmAAgAgRApIAmAAIAAgfIgmAAgAiCgHIAAgHIAzAAIALgLIARANQADAEgFABgAgWgxQgBgRgJgQQgDgFAGADQAWAVAAATQAAAKgIAAQgIAAABgPgAiAgmIAAgHIAtAAIAMgMIAQANQAEAFgGABgABqhJQgHgNgOgKQgFgEAJABQAlANgCAPQgBAHgGAAQgGAAgFgJgAiLhGIAAgHIBDAAIAPgPIATAOQAHAGgHACgAgmhXIAAgHIAhAAIAAgkIARAEQAKADgOAFIAAAYIAMAAIAMgNIARALQAHAGgHADgAh/hmIAAgHIArAAIANgMIAQALQAHAGgHACg");
	this.shape_54.setTransform(375.7,300.1);

	this.shape_55 = new cjs.Shape();
	this.shape_55.graphics.f("#000000").s().p("AiBB9QBIgzAChFIhIAAIAAgFIBJAAIAAg5IgdAAQgPAXgMALQgEABABgEQAbgpAOg9IAYAJQAGAGgQADIgVAtIA+AAIANgMIAOALQAHAGgHADIgwAAIAAA5IAfAAIAOgQIASAOQAHAEgHADIhAAAQgCAVgHAUQAcAOAUAUQAKALAAAKQAAAMgGAAQgHAAgFgNQgIgYgigZQgWAzg3AbQgFAAADgEgAAjBvIAAi7IARAKIA1AAIAHgJIAQALQAIAGgMADIAACXQgPAOAAgNIAAgQIg7AAIAAAcQgIAHgEAAQgDAAAAgFgAAyBKIA7AAIAAiFIg7AAg");
	this.shape_55.setTransform(345.3,299.6);

	this.shape_56 = new cjs.Shape();
	this.shape_56.graphics.f("#000000").s().p("Ah5B9IAAkAIARAMIDEAAIAIgKIATAMQAKAHgSADIAADiQgPAOAAgMIAAgMIjKAAIAAAPQgIAIgEAAQgDAAAAgHgAhqBmIDKAAIAAjWIjKAAgAhVBAIAAgHIBDAAIAAhCIg1AAIAAgHIA1AAIAAg2IhBAAIAAgHIB+AAIANgNIAQAMQAHAGgHACIhLAAIAAA2IAlAAIALgLIARAMQADAFgGABIg+AAIAABCIA2AAIAPgPIATAOQAHAGgHACgAAiAkQgLgRgNgJQgDgDAGAAQAjAJAAASQAAAJgGAAQgFAAgDgHg");
	this.shape_56.setTransform(316.4,300.5);

	this.shape_57 = new cjs.Shape();
	this.shape_57.graphics.f("#000000").s().p("AgNB+IAAhqIhSAAIAAANQgQAOAAgNIAAh5IASAKIBQAAIAAg3IATAEQANAEgTAFIAAAqIBSAAIAIgKIATANQAJAHgRACIAABfQgQAOAAgNIAAgLIhVAAIAABpQgGAIgEAAQgDAAAAgHgAAAANIBVAAIAAhTIhVAAgAhfANIBSAAIAAhTIhSAAg");
	this.shape_57.setTransform(286.5,300.2);

	this.shape_58 = new cjs.Shape();
	this.shape_58.graphics.f("#000000").s().p("AhFBlQgNgNAAgQQABgTASgSQATgRAcgQQgOgOAAgeQAAg2gCgGQgFgMgMAAQgEgCAEgDQAUgCAQANQAGAFgFAEQgDAEAAAKIAAA9QAAAUAGAEQAfgNAjgLQAKgCgHgJQgCgEgGgDQgEgDAGgBQANABAIAKQAHAKABAHQgBAGgIAAQg0ALgjAPQggAPgRASQgLAMAAALQAAAZAeAIQANAEAkAAQAjAAAOgFQAMgFAHAFQAEAEAAAEQAAAFgHABQgVAEg3AAQgtAAgTgTg");
	this.shape_58.setTransform(260.6,299.7);

	this.shape_59 = new cjs.Shape();
	this.shape_59.graphics.f("#000000").s().p("ABVB8QgEgIgKgOIieAQQgHAWgGgOIgLgWIA1gBIAYhDIhgAAIAAgHIDYAAIAPgPIATAOQAHAGgHACIiGAAIgjBCIBzgGQgPgQgTgOQgGgEAIABQAfAMAWASQAQAOAAAQQAAALgIAAQgGAAgEgKgAiFgLQBOgtAvhNIAXAKQAGAKgRgEQAsA6BXAfQgOAFgHAMQhNgoglg/QhCBUhBAXQgGAAAEgEgAhKgRIAAgHIBoAAIAMgNIARAMQAHAGgHACg");
	this.shape_59.setTransform(234.6,299.7);

	this.shape_60 = new cjs.Shape();
	this.shape_60.graphics.f("#000000").s().p("AhsBVQBwg8AxhdQACgEgGAAQhWAMgFAHQgCADgEAAQgCAAgIgHQgSgPACgIQAAgGAFAEQAGALAMAAQAcAABLgJIALgJQAJAGAIAHQAFAEAAAEQAAAEgLAAQgWAjgYAdQAnALAZAZQAUAUAAAMQAAAKgJAAQgFAAgHgMQgLgRgOgOQgQgRgagQQg5A7hHAdIgEAAQgFAAAFgFg");
	this.shape_60.setTransform(206.8,300.1);

	this.shape_61 = new cjs.Shape();
	this.shape_61.graphics.f("#000000").s().p("AiABrQByg8AvhdQACgEgGAAQhWAMgFAHQgCADgEAAQgCAAgIgHQgSgPACgIQAAgGAFAEQAGALAMAAQAcAABLgJIALgJQAJAGAIAHQAFAEAAAEQAAAEgLAAQgWAjgYAbQAnANAZAZQAUAUAAAMQAAAKgJAAQgFAAgHgMQgLgRgOgOQgQgRgagQQg5A7hHAdIgEAAQgFAAAFgFgABPhEQgFgHgSgPQgBgBAAAAQAAgBAAAAQAAAAAAgBQABAAABgBQAQAFASAMQAKAHAAAKQAAAJgHAAQgEAAgLgRgAB3hOIgJgMQgJgJgOgJQgDgDAEAAQAbAFAKAJQAHAHAAAIQAAAGgGAAQgFAAgCgCg");
	this.shape_61.setTransform(181.8,297.9);

	this.shape_62 = new cjs.Shape();
	this.shape_62.graphics.f("#000000").s().p("AhxA8QgJgHgEgKQAAgIAFAFQAIAJANAAQAcABBHgHIAAg+QAAgJgDgHQgDgHgLgGQgvAGgEADQgGADgEAAQgCAAgKgIQgKgKAAgHQABgHACAEQAHALAQgBIAXAAQA0gEA5gDIAQgGQAJADAHAGQAGAFAAADQAAAEgHgCQgggFg9AEIAQAKQAIAEAAAEQAAAEgHACIgDBCIBJgBQALAAAHgHQAIADAJAHQAKAHAAAFQAAAFgJgDQgUgFgSAAQhMgGhSAPQgKACgEACQgCAEgGgBQgDABgKgJg");
	this.shape_62.setTransform(153.9,300.2);

	this.shape_63 = new cjs.Shape();
	this.shape_63.graphics.f("#000000").s().p("AAYByQgHgIACgIQAEgNAAgIIAAhlQhDAyg5AWQgJAAAHgHQB3g/A6hLQAFgGgBgGQgBgDgKgFQgHgCAKgBQASABAKANQAJAIAAAEQAAAFgHgBQgGAAgGAFQgVAYghAaQAaAJgWAEIAACFQAAAKgFAAQgDABgGgIg");
	this.shape_63.setTransform(127.8,300.2);

	this.shape_64 = new cjs.Shape();
	this.shape_64.graphics.f("#000000").s().p("Ag5CJIAAkRIByAAIAAAzIg/AAIAADegAguB+IAeAAIAAjeIA/AAIAAgdIhdAAg");
	this.shape_64.setTransform(109,299.7);

	this.shape_65 = new cjs.Shape();
	this.shape_65.graphics.f("#000000").s().p("AhxB1QgBgPAKgHQALgHAOgNQBGhBAkgjQAJgKgNADQgiAGggAKQgKAEgRAJQgIADgIgGQgLgLAEgTQAEgJAAAJQACAKADADQAEAEAHAAQAJAAAMgEQAogMAqgFIAGgFQAEgCAEACQALAGADADQAGAHgIABQgJACgEADIhOBHQAJgDAKAAQAOAAAFAHQAHAIABAOQADAYADAGQAFAHAXAAQAnAAAJgFQAKgEAIAJQAIAMgLAAIhDAAQggAAgHgSQgCgGgBgcQgBgRgTAAQgRAAgOAOQgoAogHAJQgEAFgEABIgCAAQgEAAAAgGgAgmhJQAOgHATgEQgcgJgLgbQAAgBAAAAQABgBAAAAQAAAAABAAQABAAABABQALAUAfAEQAPADAFAKQAHAPgPgEQgTgGggAJIgBABQgBAAAAgBQgBAAAAAAQAAgBABAAQAAgBABgBg");
	this.shape_65.setTransform(310.4,263.9);

	this.shape_66 = new cjs.Shape();
	this.shape_66.graphics.f("#000000").s().p("AghB4QgcgHgOgPQgNgPAAgPQAAgTAMgLQAUgTAoAAQAQAAAOACQAZAEAMADQAHADgFgHQgZgggWgiQggAHgYACIgLACQgGABgFgFQgOgNgCgEQgCgGAGADQALALAUAAQAVAAAggIIgSggQgEgHgGgFQgHgGAHgHQAMgMAMgEQAHAAgDADQgHAEgCAMQgCAHAGAKQAKAVAIAMQAVgFAfgOQAGgDAJACQAFABADAEQAEADgHAEQgRAGgxANQAMATAVAaQANASAHAHQAEAFAHAFQAEACABAFQACAJgBACQgEAJgJgFQgSgOgXgHQgdgKgTABQgnAAgQAQQgJAJAAAKQAAATAMALQAWARAqABQAhACAJgEQAKgDAGADQAFAEADAFQACAFgHACQgOACgaAAQgdAAgYgGg");
	this.shape_66.setTransform(285,264.2);

	this.shape_67 = new cjs.Shape();
	this.shape_67.graphics.f("#000000").s().p("Ah2B9IAAj/IATALIC/AAIAHgKIARAMQAHAGgMACIAADPQAAANgIAIQgHAHgHAAQgHAAAAgGQAAgHgFgBIgWgFQgGgCAGgCIAeAAQALAAAAgLIAAjMIjHAAIAADsQgHAHgEAAQgEAAAAgGgAhBBVIAAhjIAUAEQAJAGgOACIAABBIAlAAIAAhcIhEAAIAAgHIBaAAIAUhEIAVAMQAHAGgQABIgZAxIAfAAIAPgPIATAOQAHAGgHACIhRAAIAABcIAmAAIAAhMIAUAEQAKAGgOACIAABRQgQAOAAgNIAAgLIhYAAIAAAOQgIAHgEAAQgDAAAAgGgAgsg+QgCgRgQgQQgCgEAGACQAgAPAAAXQAAAMgHAAQgJAAgCgPg");
	this.shape_67.setTransform(259.2,265.1);

	this.shape_68 = new cjs.Shape();
	this.shape_68.graphics.f("#000000").s().p("AgtBvIAAh0QgrAngrAUQgHABAFgGQBXg0AphbIhyAAIAAgHIDZAAIAQgQIASAPQAHAFgHADIh2AAQgUAsgbAfIAHAGIBlAAIAHgKIAQAMQAHAGgLACIAABoQgQAOAAgNIAAgTIhsAAIAAAbQgIAIgDAAQgEAAAAgHgAgeBMIBsAAIAAhSIhsAAg");
	this.shape_68.setTransform(228.6,265.3);

	this.shape_69 = new cjs.Shape();
	this.shape_69.graphics.f("#000000").s().p("AgzB8QgHgDAHgEQBTgCAfgfQAMgNAAgVQAAgSgJgKQgTgTgcAAQgmAAgcAdQgRARgEARQgCAKgIgFQgNgHABgWQABgdAFgWQACgNAAgMQAAgJgDgFQgEgGAFgHQAJgOAWgFQALgCASAAQAAAAAAAAQABgBAAAAQAAAAAAgBQAAAAAAgBQgBgDgIgBQgZgFgNgbQAAgBAAgBQAAAAABAAQAAAAABAAQAAAAABABQAOARAkAHQAUAFACATQABAKgIgEQgPgHgLAAQghAAgNAMQgIAJAIAIQAHAHgDAMQgHAXABAsQAAAHAFgHQApgqAvAAQAoAAAUASQAPAQAAAVQAAAXgRARQghAfhYAAIgFAAg");
	this.shape_69.setTransform(428.5,229.1);

	this.shape_70 = new cjs.Shape();
	this.shape_70.graphics.f("#000000").s().p("Ah/BrIgBgJQAAgKAHgIQAHgGAJgUQAagyAUgrQgjAGgKAFQgHAEgFgFQgMgIAAgRQAAAAAAgBQABAAAAAAQABAAAAAAQABABAAAAQAGAOANAAQAIgBAqgGIAMgbQAGgRgHgJQgGgGgNgCQgEgCAEgCIARABQANAEAJAJQAKALgLACQgIATgKARIAWgCQAQAAAGAIQAJANAAAeQAABZgpAWQgMAFAAgKQAAgIgEgDIgYgSQgCgFAEACIAbANQAMAHAJgOQALgPAFgWQAGgcAAgWQAAgVgEgHQgFgJgNAAQgMAAgNACIg3B6QgEAGgHASQgDAJgFAAQgEAAgCgGgABvArQgHgMgKABIgiACQgHgBAFgDIAogGQAJgBgCgGQgCgRgPgTQgOgTgXgNQgFgFAIABQAUAJAWARQAdAYAEAfQABAMgFAGQgDAFgDAAQgEAAgEgGg");
	this.shape_70.setTransform(402.5,229.4);

	this.shape_71 = new cjs.Shape();
	this.shape_71.graphics.f("#000000").s().p("AgwBuQgDgIAEgPQAEgogBiJQAAgMgEgGQgDgFgNgBQgFgCAFgDQAIgCAOAEQAJADAHAFQAHAEAAAFQAAAEgEABQgFABAAAFQgDAeABAiQAOABAVAGQAcAIARALQARAOAAAKQAAAKgIAAQgFAAgIgKQgXgdg1gQIAACAQAAANgGAAQgHAAgFgLg");
	this.shape_71.setTransform(379.8,229.5);

	this.shape_72 = new cjs.Shape();
	this.shape_72.graphics.f("#000000").s().p("AhOBPQBugtAihkQADgGgMgGQgFgCAHgCQALACAHAEQAQAKAAAIQAAACgGAAQgGAAgDAIQgvBihrAjQgHAAAFgGgAg9gVQgEgNgEgFQgHgKgPgKQgBgBAAgBQAAAAAAgBQAAAAABAAQAAgBABAAQAJADAMAGQAJAGAGAGQAKAJgBAJQgCAJgFAAQgGAAgDgGgAgJgrQgHgQgGgIQgGgFgNgJQgDgDAEAAQAOACAPAJQAPAMAAAPQAAAJgFgBQgGABgCgGg");
	this.shape_72.setTransform(359.5,234.1);

	this.shape_73 = new cjs.Shape();
	this.shape_73.graphics.f("#000000").s().p("AhMBUIgNgPQAEgCACgFIAAh+QAAgLgEgFQgEgGgMgBQgFgCAFgDQAQgBAOAGQAPAGAAAEQAAADgGAEQgFAEAAAFIAAB/QBVgkBWhJQAFgBgBAFQg2A8hwA9QgDALgEAAQgCAAgHgJg");
	this.shape_73.setTransform(336.2,229.4);

	this.shape_74 = new cjs.Shape();
	this.shape_74.graphics.f("#000000").s().p("AhqB2QBtgnAth/QADgHgGAAQgaAChpANQgEACgGAEQgBAEgEAAQgDAAgMgLQgKgIgBgJQAAgGAFAEQAFAJAPAAICJgLQAOgCAEgIQAOAHAJAJQAGAGAAADQAAAEgIAAQgIAAgBAFQg0CAh0AiQgHAAAEgGgABRhLQgFgHgSgPQgBgBAAAAQAAgBAAAAQAAgBAAAAQABAAABgBQAQAFASAMQAKAHAAAKQAAAJgHAAQgEAAgLgRgABzhaQgFgFgEgHQgJgJgOgIQgDgEAFAAQAbAFAJAJQAHAHAAAIQAAAGgGAAQgFAAgCgCg");
	this.shape_74.setTransform(309.4,228.1);

	this.shape_75 = new cjs.Shape();
	this.shape_75.graphics.f("#000000").s().p("Ag/ByQBpgqgBhWIAAhSQgBgJgEgFQgDgFgMgBQgBgBAAAAQAAgBAAAAQAAAAABgBQAAAAABAAQATgDAPAHQALAFAAADQAAAGgLAGIAABRQABBgh2AnQgIgCAGgFgAgqAUQgEgHABgDIACgSIAAhPQAAgIgEgEQgFgFgJgBQgFgDAFgCQASgBANAHQAKADAAAFQAAAEgEABQgDABAAAJIAABYQABATgJAAQgDAAgEgGg");
	this.shape_75.setTransform(285.4,229.7);

	this.shape_76 = new cjs.Shape();
	this.shape_76.graphics.f("#000000").s().p("AgKBSQgmAohPAKQgHgCAEgEQBOgOAegnQgYgXgTgaIAIgFQAOAVAcAWQAMgSABgmIhOAAIAAARQgQAOAAgNIAAhuIASALIBMAAIAAg5IATAEQANAFgTAFIAAArIBEAAIAIgLIATANQAKAHgSADIAABQQgPANAAgMIAAgMIhIAAQAAArgNAWQA4AoBOgBQgQALgDAMQhFgJg2gqgAALAAIBIAAIAAhEIhIAAgAhQAAIBOAAIAAhEIhOAAg");
	this.shape_76.setTransform(262.1,229.1);

	this.shape_77 = new cjs.Shape();
	this.shape_77.graphics.f("#000000").s().p("AhyCAQBIgbAAgwIAAgrQgoApgwAUQgKAAAHgFQBBgjApg9IgqAAIAAAUQgPANAAgLIAAh7IASALICEAAIAHgJIARALQAHAHgMABIAABgQgPAOAAgNIAAgRIg2AAQAwAzBJANQgOAGgHANQgmgQgbgUIgHADIAABpQgPAOAAgNIAAh4IAOAEQgWgTgOgVIgOAAQgQAYgPAMIAQACQAKAGgPADIAAAiQAAA7hWAWQgGABAFgFgAAHglIA/AAIAAggIg/AAgAhFglIA+AAIAAggIg+AAgAAHhNIA/AAIAAgkIg/AAgAhFhNIA+AAIAAgkIg+AAg");
	this.shape_77.setTransform(232.1,229.7);

	this.shape_78 = new cjs.Shape();
	this.shape_78.graphics.f("#000000").s().p("AhTB8IAAiiIg1AAIAAgHIA1AAIAAhNIAUAEQAKAGgOACIAABBIA2AAIAAhUIASAEQAKAGgOACIAABIIAyAAIAAhSIAUADQAKAGgPACIAABHIAbAAIASgSIAWAQQAHAGgHADIhDAAIAABfQgPAOAAgNIAAgSIgyAAIAAAbQgNAOgBgMIAAhrIg2AAIAACHICZAAIASgSIAWARQAHAFgHADIjBAAIAAATQgJAHgDAAQgEAAAAgGgAABAhIAyAAIAAhHIgyAAg");
	this.shape_78.setTransform(202.2,229.8);

	this.shape_79 = new cjs.Shape();
	this.shape_79.graphics.f("#000000").s().p("AhwBqQgJgdABgsQABguAPg1QACgIAAgLQAAgLgOgGQgFgDAFgBQALAAAHAFQAEACAMANQAFAFgFAFQgCACgDALQgYBAAAAlQAAAUACADQADAEACgFQANghAOgbQAGAAgCACQgMAbgHAbQgEAOAAAJQAAANACAMQABAMgKAAQgGAAgDgKgAgWBeQgIgIAAgLQAAgIAJgHQAMgIAXAAQAUAAAPADQAAg/gDgkQgpAGgbAAQgKAAgHgGQgOgMgDgKQgBgGAFAEQANAUASAAQAXAAArgGQgBgdgBgLQgBgNgVgBQgLAAAKgFQAIgDAKABQAMABALAHQAEAEgGAGQgCACAAAJIABAeQAjgFAEgCQAGgEAGAEIAIAFQADAFgHABQgcAFgaACQAEA1AAAyIAyASQAGADABAEQADAHgCAEQgCAHgHgFQghgUgRgGQgEATgNAIQgLAJgUAAQgYAAgMgMgAgSBEQgEAEAAAEQAAAHAEAEQAKAKASAAQATAAAHgHQAKgKACgNQgSgHgTAAQgVAAgIAIg");
	this.shape_79.setTransform(173,229.9);

	this.shape_80 = new cjs.Shape();
	this.shape_80.graphics.f("#000000").s().p("Ah7B2IAAjyIASAMIDGAAIAIgKIATAMQAKAIgSACIAADUQgPAOAAgNIAAgQIjNAAIAAAUQgIAIgDAAQgEAAAAgHgAhsBaIDNAAIAAjDIjNAAgAg+AzIAAhwIASAKIBFAAIAIgKIATAMQAKAHgSADIAABQQgPAOAAgNIAAgNIhMAAIAAAVQgHAIgEAAQgEAAAAgHgAgvAWIBMAAIAAhCIhMAAg");
	this.shape_80.setTransform(143.3,230);

	this.shape_81 = new cjs.Shape();
	this.shape_81.graphics.f("#000000").s().p("AAXCBIAWhbIiMAAIAAgHICKAAIAFgIIATAJQALAFgSAEIgWBaQgHAFgEAAQgEAAAAgHgAiGANQBHgyAwhiIAaAHQAJAEgSAFQA5BIBNAZQgRAIgDAIQhEgfgxhPQgxBUhQAzIgCAAQgFAAADgGgAg7gPIAAgHIBPAAIANgNIARAMQAHAGgHACg");
	this.shape_81.setTransform(112.5,229.4);

	this.shape_82 = new cjs.Shape();
	this.shape_82.graphics.f("#000000").s().p("AAMAbIgNgbQgHgKgVgSQgGgFAHAAQAcAIAWAZQALAIAAALQAAAHgFAFQgDADgEAAQgGAAgDgHg");
	this.shape_82.setTransform(414.7,204.5);

	this.shape_83 = new cjs.Shape();
	this.shape_83.graphics.f("#000000").s().p("AABBUQgjgeAAgwQAAgqAsglQAGgEgGAAIhDAOQgOACgOAHQgLAFgDgBQgGgCgGgEQgNgKgBgKQACgIADAHQAFAKATgBQAKAAAWgFIB4gWQASgDAHgGQAHgGAJAGIAOAKQAGAGgJACQhIgCggAgQgcAeAAAdQAAAjAXAXQAXAZAfABQAMAAAEAFQAEAGAAAEQAAAGgJAAQghAAgegYgABQgLQgIgSgWgOQgDgEAEABQAUAEAPALQAHAGACAJQADAJgHACIgDABQgFAAgDgHgABvgdQgIgTgXgOQgCgEADACQAUADAQAMQAHAGACAIQACAJgHADIgCAAQgGAAgCgGg");
	this.shape_83.setTransform(394.8,194.7);

	this.shape_84 = new cjs.Shape();
	this.shape_84.graphics.f("#000000").s().p("AhFBlQgNgNAAgQQAAgTATgSQATgRAcgQQgOgOAAgeQAAg2gCgGQgFgMgMAAQgEgCAEgDQAUgCARANQAFAFgEAEQgEAEAAAKIAAA9QAAAUAGAEQAfgNAjgLQAKgCgHgJQgCgEgGgDQgFgDAGgBQAOABAIAKQAHAKABAHQgBAGgIAAQg0ALgjAPQghAPgQASQgLAMAAALQABAZAdAIQANAEAkAAQAjAAANgFQANgFAHAFQAEAEAAAEQAAAFgHABQgVAEg3AAQgtAAgTgTg");
	this.shape_84.setTransform(370.2,193.9);

	this.shape_85 = new cjs.Shape();
	this.shape_85.graphics.f("#000000").s().p("AgQBmQgrAAgVgZQgMgPgEgWQACgFADAGQAGAPALAMQAUAUAnAAIA3AAQATAAALgDIALgCQAHAAAHAJQAHAKgPAAIhnAAgAgugnQASgOAXgLQgcgCgPgHQgUgKgJgPQAAgGAEAFQASAUA2AAQAlAAAKgEQAFgBAFAFIAHAIQAFAIgKAAIgZAAQgOAAgMAEQgVAHgcAPIgEACQgBAAAAgBQAAAAAAAAQAAgBAAAAQABgBAAgBg");
	this.shape_85.setTransform(348,194.4);

	this.shape_86 = new cjs.Shape();
	this.shape_86.graphics.f("#000000").s().p("AAHBUQgigeAAgwQAAgqArglQAGgEgGAAIhDAOQgOACgOAHQgKAFgEgBQgGgCgGgEQgMgKgCgKQADgIACAHQAGAKATgBQAJAAAWgFIB4gWQATgDAHgGQAHgGAIAGIAOAKQAGAGgIACQhJgCgfAgQgdAeAAAdQAAAjAWAXQAYAZAgABQAMAAADAFQAFAGAAAEQAAAGgKAAQggAAgfgYg");
	this.shape_86.setTransform(323.4,194.7);

	this.shape_87 = new cjs.Shape();
	this.shape_87.graphics.f("#000000").s().p("AgSA7QBHgJAYgaQANgOAAgRQAAgRgJgKQgTgUgeAAQglAAg1AoQgJAHgFAGQgGAEgJgFQgSgQABgEQACgFACADQAGAIAHgBQAGABAHgGQAegTASgJQAcgOAeABQAgAAAYAUQARAPAAAaQAAARgLANQgfAjhRABQgHgDAHgCg");
	this.shape_87.setTransform(296,197.6);

	this.shape_88 = new cjs.Shape();
	this.shape_88.graphics.f("#000000").s().p("AAMAbIgNgbQgHgKgVgSQgGgFAHAAQAcAIAWAZQALAIAAALQAAAHgFAFQgDADgEAAQgGAAgDgHg");
	this.shape_88.setTransform(270.1,204.5);

	this.shape_89 = new cjs.Shape();
	this.shape_89.graphics.f("#000000").s().p("AgzB/QAzgUAZgfQAageAAguQAAgagNgMQgJgIgMAAQgWAAgYAXIgRASQgGAFgFgBQgKgHAAgPQABgRACgIQABgBABAAQAAAAABAAQAAAAAAABQABAAAAABQgBATAEADQAFAFAFgDIAYgRQAVgOAXAAQAQAAAOANQAQAPAAAhQAAAvggAgQggAeg1AQQgGAAAFgFgAgmhRQAMgKATgMQgZAAgRgYQgBgEADABQATAQAXAAQAMAAAKgCQAMgCAEAKQAFALgOAAQgVAAgLAEQgKAEgRAKIgCABQAAAAAAgBQgBAAAAAAQAAAAAAgBQAAAAAAgBg");
	this.shape_89.setTransform(254.4,194.4);

	this.shape_90 = new cjs.Shape();
	this.shape_90.graphics.f("#000000").s().p("AgQBmQgrAAgVgZQgMgPgEgWQACgFADAGQAGAPALAMQAUAUAnAAIA3AAQATAAALgDIALgCQAHAAAHAJQAHAKgPAAIhnAAgAgugnQASgOAXgLQgcgCgPgHQgUgKgJgPQAAgGAEAFQASAUA2AAQAlAAAKgEQAFgBAFAFIAHAIQAFAIgKAAIgZAAQgOAAgMAEQgVAHgcAPIgEACQgBAAAAgBQAAAAAAAAQAAgBAAAAQABgBAAgBg");
	this.shape_90.setTransform(234.3,194.4);

	this.shape_91 = new cjs.Shape();
	this.shape_91.graphics.f("#000000").s().p("AhABfQgUgHgNgfQgJgWAAggIAAg9QAAgbgQgHQgFgCAGgBQAOABAOAMQAMAJgJAJQgDAfAAAUQAAA0ANAVQAHAKAGgKIArhIQAFgGAAAIIggBDQgIARADAKQAEAMgHAAIgFgBgABpAaQgDgdgOgaQgNgYgZgVQgDgEAFAAQAZANAOAPQAiAmAAAiQAAANgKAAQgJAAgBgJg");
	this.shape_91.setTransform(208.7,194.5);

	this.shape_92 = new cjs.Shape();
	this.shape_92.graphics.f("#000000").s().p("AAHBUQgigeAAgwQAAgqArglQAGgEgGAAIhDAOQgOACgOAHQgKAFgEgBQgGgCgGgEQgMgKgCgKQADgIACAHQAGAKATgBQAJAAAWgFIB4gWQATgDAHgGQAHgGAIAGIAOAKQAGAGgIACQhJgCgfAgQgdAeAAAdQAAAjAWAXQAYAZAgABQAMAAADAFQAFAGAAAEQAAAGgKAAQggAAgfgYg");
	this.shape_92.setTransform(181.1,194.7);

	this.shape_93 = new cjs.Shape();
	this.shape_93.graphics.f("#000000").s().p("AhABfQgUgHgNgfQgJgWAAggIAAg9QAAgbgQgHQgFgCAGgBQAOABAOAMQAMAJgJAJQgDAfAAAUQAAA0ANAVQAHAKAGgKIArhIQAFgGAAAIIggBDQgIARADAKQAEAMgHAAIgFgBgABpAaQgDgdgOgaQgNgYgZgVQgDgEAFAAQAZANAOAPQAiAmAAAiQAAANgKAAQgJAAgBgJg");
	this.shape_93.setTransform(153,194.5);

	this.shape_94 = new cjs.Shape();
	this.shape_94.graphics.f("#000000").s().p("AhTCBIAAhZIASAJICAAAIAHgIIAPALQAIAGgNACIAABAQgPAOAAgMIAAgKIiFAAIAAAMQgIAHgDAAQgEAAAAgGgAhEBtICFAAIAAgWIiFAAgAhEBQICFAAIAAgYIiFAAgAiFAdIAAgHIB0AAIAAgWIhXAAIAAgHIBXAAIAAgbIhPAAIAAgHIBPAAIAAgbIh1AAIAAgHIB1AAIAAgZIhQAAIAAgHIBQAAIAAgbIANADQASADgQAGIAAAPIA5AAIAHgIIAPAKQAIAGgNADIAAAVIAZAAIAPgPIATAOQAHAFgHADIg7AAIAAAoQgPAOAAgNIAAgHIg7AAIAAAbIBOAAIANgNIAQAMQAHAFgHADIhrAAIAAAWIBkAAIAPgPIATAOQAHAGgHACgAgCgpIA7AAIAAgbIg7AAgAgChLIA7AAIAAgZIg7AAg");
	this.shape_94.setTransform(124.2,194.3);

	this.shape_95 = new cjs.Shape();
	this.shape_95.graphics.f("#000000").s().p("AhdByQgWgPAAhBQAAgpAMg7QADgKAAgPQAAgQgMgDQgGgFAIAAQASAFAJAPQADAEgDAHQgOApgCALQgHAfAAAVQAAAYADAOQABAAABABQAAAAABAAQAAAAABAAQABgBAAAAQANgoANgSQAGgBgDADQgJASgIAlQgFAUAFANQAGAQgDAGQgCAEgDAAIgFgCgAAiBYQgkAAgPgPQgPgPAAgWIABgTQACgFADAFQABAhAKAKQAPAPAeAAIAlAAQASAAALgEQAMgFAHAMQAEAIgKABIgcABIgvAAgAAAggQANgSAUgNQAEgEgGAAQgjADgWgOQgGgFAIABQAUAFAMAAQAhAAAfgHQAOgEAFAIQAHAMgOAAQgnAAgqAnIgCABQgBAAAAAAQAAgBAAAAQAAgBAAAAQAAgBAAgBg");
	this.shape_95.setTransform(407.6,159.2);

	this.shape_96 = new cjs.Shape();
	this.shape_96.graphics.f("#000000").s().p("AgsCCQAOgLAKgMQAYgdABgpQgHAOgPAAQgNAAgLgLQgIgIAAgQQAAgQAMgKQAJgKAOAAQALAAAGAFIAAgnQg8AKgfAJIgQAGQgHADgGgEQgNgKgGgRQAAgGAFAFQAGAKAQAAQARAAAigGQAbgEAigEIAAgfQAAgbgVgDQgFgCAFgCQASgDALAIQAGAEAFAHQAEAGgFACQgEAEAAAkIBGgGIAYgFQAGgBAFAFQANALACADQACAHgJgCQgYgGgkAAQgXAAgeACIAAAzQAEAJAAAVQAABKg/AhIgCAAQgBAAAAAAQgBAAAAAAQAAgBABgBQAAAAABgBgAghgEQgFAGAAAMQAAASAJAIQADAEAJAAQAIAAAFgFQAIgKAAgTQAAgYgSAAQgNAAgGAKgABNhYQgIgSgXgOQgCgEADABQAUAEAQALQAHAGACAJQACAJgHACIgDABQgFAAgCgHgAByhhQgIgTgWgOQgDgDAEABQAUADAPAMQAHAGADAIQACAKgHACIgEAAQgEAAgDgGg");
	this.shape_96.setTransform(377.4,159);

	this.shape_97 = new cjs.Shape();
	this.shape_97.graphics.f("#000000").s().p("Ah/BrIgBgJQAAgKAHgIQAHgGAJgUQAagyAUgsQgjAIgKAEQgHADgFgEQgMgIAAgQQAAgBABgBQAAAAAAAAQABAAAAAAQABABAAABQAGAMANAAQAIAAAqgGIAMgbQAGgRgHgIQgGgIgNAAQgEgDAEgCIARABQANAEAJAJQAKALgLACQgIATgKARIAWgCQAQAAAGAIQAJANAAAeQAABZgpAWQgMAFAAgKQAAgIgEgDIgYgSQgCgFAEABIAbAPQAMAFAJgNQALgPAFgWQAGgcAAgWQAAgVgEgHQgFgJgNAAQgMAAgNACIg3B6QgEAGgHASQgDAJgFAAQgEAAgCgGgABvArQgHgMgKACIgiACQgHgCAFgDIAogGQAJgBgCgGQgCgRgPgTQgOgUgXgMQgFgFAIACQAUAHAWASQAdAXAEAhQABALgFAGQgDAFgDAAQgEAAgEgGg");
	this.shape_97.setTransform(348.3,158.9);

	this.shape_98 = new cjs.Shape();
	this.shape_98.graphics.f("#000000").s().p("AhtCAIAAiWIAVAEQANAFgTAEIAAByIC6AAIARgRIAWAQQAHAGgHACIjhAAIAAAOQgIAIgEAAQgDAAAAgGgAg4BXIAAhxIARAJIAiAAIAAgXIiBAAIAAgHICBAAIAAgZIhSAAIAAAIQgPAOAAgNIAAhEIARAJIClAAIAIgLIATANQAJAHgRACIAAAsQgQAOAAgNIAAgGIhLAAIAAAZIBXAAIAPgQIATAOQAHAGgHADIh5AAIAAAXIA0AAIAIgKIATAMQAJAHgRADIAABXQgQAOAAgNIAAgGIhoAAIAAAIQgIAIgEAAQgDAAAAgGgAgpBGIBoAAIAAgXIhoAAgAgpAoIBoAAIAAgXIhoAAgAgpAKIBoAAIAAgUIhoAAgAAjhPIAwAAIAAgkIgwAAgAgYhPIAsAAIAAgkIgsAAgAhXhPIAwAAIAAgkIgwAAg");
	this.shape_98.setTransform(319.1,159.5);

	this.shape_99 = new cjs.Shape();
	this.shape_99.graphics.f("#000000").s().p("AhEBsQgJgKAAgKQAAgQAOgOQATgSAmgUQAAgTgIgGQgFgFgKAAQgdAAgpAwQgEAEgDAAQgGAAAAgLQAAgKAEgCQAKgFAJgLQAVgTAZgrIgbACIgRABQgEAAgIgIQgHgGAAgIQACgFACAGQAHALAUAAQAUAAARgDQAJgRABgLQACgQgUgEQgIgBAHgDQAVgDAVAQQAFAEgGAGQgGAFgOAYQAagEAPgHQAFgEAEAAQADAAAFAFQADABAAAFQAAADgIABIg5AKIggAvQgDAGAFgDQATgJANAAQAQAAAJAIQAIAKABAOQA7gaAQgKQAGgCgDgEQgHgEgKgDQgHgCAHgCQATgBAWAMQAFAEAAACQAAAEgFACQgZAIhNAgIAAAyQAAAKgHAAQgFAAAAgHIAAguQgfAOgUAUQgLALAAAJQAAAJAGAFQALALAmAAQAlAAAagGQAIgDAFAAQANAAAAALQAAAFgIABQgTAFg4AAQguAAgPgPg");
	this.shape_99.setTransform(291.6,158.8);

	this.shape_100 = new cjs.Shape();
	this.shape_100.graphics.f("#000000").s().p("ABRB9QAAgGgGgCIgUgFQgGgCAGgDIAfAAQALAAAAgKIAAiJIhHAAIAAAJQgQAOAAgNIAAhkIASALIBCAAIAHgKIAQAMQAHAGgMACIAADUQAAAOgIAHQgHAGgJABIgCAAQgFAAAAgGgAAagvIBHAAIAAgeIhHAAgAAahUIBHAAIAAgcIhHAAgAh3B8IAAj+IASALIA9AAIAHgKIAQAMQAHAGgMACIAABMQgPAMAAgKIAAgJIhDAAIAACjQgHAHgEAAQgEAAAAgGgAhogvIBDAAIAAgeIhDAAgAhohUIBDAAIAAgcIhDAAgAg2BlIAAh0IARALIA5AAIAHgKIAQAMQAHAEgMACIAABYQgPAOAAgNIAAgRIg+AAIAAAYQgIAHgEAAQgDAAAAgGgAgnBFIA+AAIAAghIg+AAgAgnAdIA+AAIAAgcIg+AAg");
	this.shape_100.setTransform(263.6,159.3);

	this.shape_101 = new cjs.Shape();
	this.shape_101.graphics.f("#000000").s().p("AgOB6QAWgQAQgVQATgYAAgmIAAhDQgSAEgZAAQgTAAgJgEQgMgFgKgPQAAgBABAAQAAgBAAAAQABAAAAgBQABAAAAABQAJAJAIAEQAIADANAAIAagBIAagDIAAguQAAgTgSAAQgIAAAHgFQAIgCALAEQAKADAHAGQAGAFgHAEQgCABAAAQIAAAeQAagDAJgFQAGgEAFAEIAKAIQAEAFgGABIg2AGIAABJQAAApgZAaQgQARgZAMIgFACQgBAAAAgBQAAAAAAAAQAAgBAAgBQAAAAABgBgAhuBNQgFgQACgiQABgcACgOQAFgbADgOQADgJAAgNQAAgOgHgIQgFgHAIADQAOAKAGANQAEAHgFAJQgUAoAAAvQAAAWADAKQADAHADgKQAMgcALgbQAEgFAAAGIgNApQgFAUAAARIACAOQACANgJAAQgMAAgHgZg");
	this.shape_101.setTransform(235.3,159.2);

	this.shape_102 = new cjs.Shape();
	this.shape_102.graphics.f("#000000").s().p("AhsB7QgDgDgBgGQgEgMAEgFQAHgMAGgPQAUg4ARg5IgqAGQgHADgFgEIgIgKQgEgEAAgGQACgGACADQAIAMAPAAQAWAAATgDQALgbABgQQAAgFgDgEQgGgFgIgBQgJAAAHgEQAGgCAHAAQAKAAAQAMQAIAGgIAFQgGADgNAjQAYgEAUgMQADgEADAAQAFAAAFAHQAGAJgLACQgYAGgiAGIgxCkQgCAFgDAAIgEgBgAAtByQgsAAgOgPQgLgMAAgSQAAgLACgHQAFgJAAAJIgCANQAAAOALALQALANAcAAIAjAAQATAAAGgEQAIgFAFAEQAIAGABACQAFAJgOAAIg7AAgAAFACQAKgKAXgMQAJgEgLAAQgVAAgkAOQgGACAEgGQAXgOAcgGQAdgFAVACQAMABAAAIQAAAHgKAAQgpAAgfAZIgDACQgBAAAAgBQAAAAAAAAQAAgBAAgBQABAAAAgBgABQhFQgIgSgWgPQgDgDAEABQAUAEAPALQAHAGACAIQADAKgHACIgDABQgFAAgDgHgABxhXQgIgTgWgOQgDgEAEABQAUAEAPAMQAHAFACAJQADAJgHACIgDABQgFAAgDgGg");
	this.shape_102.setTransform(206.8,158.4);

	this.shape_103 = new cjs.Shape();
	this.shape_103.graphics.f("#000000").s().p("AgrBoQgLgKABgLQAAgJAGgHQAIgIARAAQAUAAAOAQQALALAEASQAVgEARgRQASgRAAgZQgBgbgQgOQgSgTgjAAQgjAAgmAlQgQAPgJAPQgDAFgGAAQgEAAAAgLQAAgJAKgIQAHgHBlhvQADgCgGgBQgaAEgcAKQgIAEgFAAQgCAAgKgHQgMgJgBgMQABgGAEAFQAHALAQAAQAPAAAEgBQAXgEAVgFQAMgCAFgFQADgDADAAQAGAAAIAGQAFAEAAAEQAAACgLAEQgNAGhCBHQgDAGAHgEQAZgJAYAAQAmAAAYAXQAQAPAAAbQAAAfgSATQgcAcg0AAQgfAAgNgNgAguBTQABAHAGAHQALALAkAAQgCgVgIgLQgJgJgNAAQgWAAAAAQg");
	this.shape_103.setTransform(180.2,159.4);

	this.shape_104 = new cjs.Shape();
	this.shape_104.graphics.f("#000000").s().p("AgVB7QgZgFgOgNQgSgQAAgSQAAgNAKgKQAQgTAvAAQAeAAATAFIgZgxQgaAHglAFQgRACgNAAQgHAAgGgEQgIgHgFgKQAAgGAFAFQAHAJAOAAIAegBQAagDAggHQgIgRgIgWQgMAEgeAEQgOADgHgFQgIgFgGgJQgBgIAGAFQAEAJASAAQAPAAAggHQgLgegEgHQgFgHgPAAQgBAAgBAAQAAAAAAgBQgBAAABgBQAAAAABgBQAQgGAIADIAMAHQAFAFAAAHQAAAMAFAQQAQgEAHgGQAFgGADAAQAFAAADACIAIAEQAFADgHAEQgJAEghAJQAIAVAJAQQASgFASgHQAMgEAEgGQAEgFAHADIAMAFQAEAFgHAEIgWAIIgtANQAUAhAHAJQAHAKAGADQALAGgBAIQgCAMgKgHQgMgIgRgFQgVgGgUAAQgsAAgNAPQgHAJAAAJQAAAMAMALQAQARAiABQAdABAFgCQAKgEAGAAQAHAAAGAHQAEAFgIADQgIAEggAAQgYAAgMgCg");
	this.shape_104.setTransform(156.4,159.1);

	this.shape_105 = new cjs.Shape();
	this.shape_105.graphics.f("#000000").s().p("AABBUQgjgeAAgwQAAgqAsglQAGgEgGAAIhDAOQgOACgOAHQgLAFgDgBQgGgCgGgEQgNgKgBgKQACgIADAHQAFAKATgBQAKAAAWgFIB4gWQASgDAHgGQAHgGAJAGIAOAKQAGAGgJACQhIgCggAgQgcAeAAAdQAAAjAXAXQAXAZAfABQAMAAAEAFQAEAGAAAEQAAAGgJAAQghAAgegYgABQgLQgIgSgWgOQgDgEAEABQAUAEAPALQAHAGACAJQADAJgHACIgDABQgFAAgDgHgABvgdQgIgTgXgOQgCgEADACQAUADAQAMQAHAGACAIQACAJgHADIgCAAQgGAAgCgGg");
	this.shape_105.setTransform(130.9,159.5);

	this.shape_106 = new cjs.Shape();
	this.shape_106.graphics.f("#000000").s().p("AAHBUQgigeAAgwQAAgqArglQAGgEgGAAIhDAOQgOACgOAHQgKAFgEgBQgGgCgGgEQgMgKgCgKQADgIACAHQAGAKATgBQAJAAAWgFIB4gWQATgDAHgGQAHgGAIAGIAOAKQAGAGgIACQhJgCgfAgQgdAeAAAdQAAAjAWAXQAYAZAgABQAMAAADAFQAFAGAAAEQAAAGgKAAQggAAgfgYg");
	this.shape_106.setTransform(370.9,124.2);

	this.shape_107 = new cjs.Shape();
	this.shape_107.graphics.f("#000000").s().p("AhABfQgUgHgNgfQgJgWAAggIAAg9QAAgbgQgHQgFgCAGgBQAOABAOAMQAMAJgJAJQgDAfAAAUQAAA0ANAVQAHAKAGgKIArhIQAFgGAAAIIggBDQgIARADAKQAEAMgHAAIgFgBgABpAaQgDgdgOgaQgNgYgZgVQgDgEAFAAQAZANAOAPQAiAmAAAiQAAANgKAAQgJAAgBgJg");
	this.shape_107.setTransform(342.8,124);

	this.shape_108 = new cjs.Shape();
	this.shape_108.graphics.f("#000000").s().p("AgHBJQBPgMAageQAOgQAAgWQAAgbgWgRQgXgRgeAAQgtAAg4AsIgUAQQgGAGgJgEQgKgDgHgFQgJgFgCgKQAAgFAEAEQAGAIALAAQALAAAGgDQALgGAPgLQA0gjAwAAQArAAAbAZQAVATAAAfQAAAWgRAUQgcAjhaADQgHgCAHgDg");
	this.shape_108.setTransform(313.3,125);

	this.shape_109 = new cjs.Shape();
	this.shape_109.graphics.f("#000000").s().p("AhdByQgWgPAAhBQAAgpAMg7QADgKAAgPQAAgQgMgDQgGgFAIAAQASAFAJAPQADAEgDAHQgOApgCALQgHAfAAAVQAAAYADAOQADADACgDQANgoANgSQAGgBgDADQgJASgIAlQgFAUAFANQAGAQgDAGQgCAEgDAAIgFgCgAAiBYQgkAAgPgPQgPgPAAgWIABgTQACgFADAFQABAhAKAKQAPAPAeAAIAlAAQASAAALgEQAMgFAHAMQAEAIgKABIgcABIgvAAgAAAggQANgSAUgNQAEgEgGAAQgjADgWgOQgGgFAIABQAUAFAMAAQAhAAAfgHQAOgEAFAIQAHAMgOAAQgnAAgqAnIgCABQgBAAAAAAQAAgBAAAAQAAgBAAAAQAAgBAAgBg");
	this.shape_109.setTransform(285.3,124);

	this.shape_110 = new cjs.Shape();
	this.shape_110.graphics.f("#000000").s().p("AgKB+IAAhDIg3AAIAAgHIA3AAIAAhcQg3BYhGAnQgHABAEgGQBJgzAthcIhtAAIAAgHIB3AAIAAg/IASADQAJAGgOACIAAA0IBXAAIARgSIAXARQAHAGgHACIh5AAQAuBYBVAjQgPAFgGALQhPgtglhcIAABvIAaAAIAPgPIATAOQAHAGgHACIg8AAIAABCQgGAHgEAAQgDAAAAgGg");
	this.shape_110.setTransform(255.1,123.9);

	this.shape_111 = new cjs.Shape();
	this.shape_111.graphics.f("#000000").s().p("AhsB7QgDgDgBgGQgEgMAEgFQAHgMAGgPQAUg4ARg5IgqAGQgHADgFgEIgIgKQgEgEAAgGQACgGACADQAIAMAPAAQAWAAATgDQALgbABgQQAAgFgDgEQgGgFgIgBQgJAAAHgEQAGgCAHAAQAKAAAQAMQAIAGgIAFQgGADgNAjQAYgEAUgMQADgEADAAQAFAAAFAHQAGAJgLACQgYAGgiAGIgxCkQgCAFgDAAIgEgBgAAtByQgsAAgOgPQgLgMAAgSQAAgLACgHQAFgJAAAJIgCANQAAAOALALQALANAcAAIAjAAQATAAAGgEQAIgFAFAEQAIAGABACQAFAJgOAAIg7AAgAAFACQAKgKAXgMQAJgEgLAAQgVAAgkAOQgGACAEgGQAXgOAcgGQAdgFAVACQAMABAAAIQAAAHgKAAQgpAAgfAZIgDACQgBAAAAgBQAAAAAAAAQAAgBAAgBQABAAAAgBgABQhFQgIgSgWgPQgDgDAEABQAUAEAPALQAHAGACAIQADAKgHACIgDABQgFAAgDgHgABxhXQgIgTgWgOQgDgEAEABQAUAEAPAMQAHAFACAJQADAJgHACIgDABQgFAAgDgGg");
	this.shape_111.setTransform(225.9,123.1);

	this.shape_112 = new cjs.Shape();
	this.shape_112.graphics.f("#000000").s().p("Ah8BkQAAgJAFgEQAJgLAEgIQAqhLAdhCQAEgKAAgGQAAgRgSgFQgFgEAIAAQAWABANAZQADAJgGAAIg7BsQAYgVAWgBQAjAAAAAlQAAAXACAQQACARAQAAQAXAAAagaQAVgVAWg0QAEgBABACQgNA4ggAfQgXAYgbAAQgdAAgCgUQgDgUAAgdQAAgdgXAAQgTAAgXAVQgOAOgbA8QgBAHgFgBQgIAAAAgPg");
	this.shape_112.setTransform(197.3,123.5);

	this.shape_113 = new cjs.Shape();
	this.shape_113.graphics.f("#000000").s().p("Ah1CAIAAhjIARAJIAiAAIAHgJIARALQAHAGgMACIAABAQgPAOAAgNIAAgJIgoAAIAAAXQgIAHgEAAQgDAAAAgGgAhmBhIAoAAIAAg0IgoAAgAg2B/QAfgNAQgPQANgPAAgkIAAguIAUADQAJAGgOACIAAAlQAAAkgRASQgPAQgpAMQgHAAAFgFgABFB0QgOAAAAgOIAAhjIAUADQAIAEgNAFIAABTQAAAEAFAAIAWAAQAMAAACgLIAJgnQAAgBABAAQAAAAABAAQAAAAAAAAQABAAAAABIAAApQAAAGAFADQAHAGgIAFQgGADgMAAgAgfAJQAAgFAFgEQALgPABgUQACgGACAGQACAFAAAHIBrAAIAJgKIAbAXQAFAFgKAAIgUAAQgJAIgJAHQgFACABgFIANgXIhsAAQAAATgGAIQgEAGgIAAQgGAAAAgIgAh8AGIAAgGIA1AAIANgMIARAMQAHAEgHACgAh8geIAAgHIA1AAIANgNIARALQAHAGgHADgAgMgwIAAgHIAtAAIAAghIg5AAIAAgHIA5AAIAAgmIAUADQAJAGgOACIAAAbIAtAAIARgRIAXAQQAHAGgHACIhVAAIAAAhIAcAAIAQgPIASAOQAHAGgHACgAiHhCIAAgHIBKAAIAPgPIATAOQAHAGgHACgAh8hoIAAgHIA5AAIANgNIAQAMQAHAFgHADg");
	this.shape_113.setTransform(168.3,123.6);

	this.shape_114 = new cjs.Shape();
	this.shape_114.graphics.f("#000000").s().p("AgnCCQATgKALgRQAJgRAGgbQAGgaAAgdQAAgdgFgaQgEgUgDgMQgGgNgJgLQgJgLgPgKIAAgHQAXALAPAPQASAWALAdQAMAcAAAeQAAAtgWAlQgVAmgkAQg");
	this.shape_114.setTransform(400.3,92);

	this.shape_115 = new cjs.Shape();
	this.shape_115.graphics.f("#000000").s().p("Ag5BnIAAgGQATAAARgIQAPgJAOgVQAQgWAFgZQgWAOgRAAQgWAAgOgQQgPgOAAgbQAAgaAPgUQASgZAcAAQAXAAASAUQAVAZAAAlQAAAfgQAdQgQAcgeATQgVAQgcAAgAgZhRQgKAMAAAXQAAAfANAPQAKANAMAAQAGAAAKgDQAJgDAHgGQACgRABgMQAAgOgGgQQgEgRgJgJQgJgIgJAAQgOAAgJALg");
	this.shape_115.setTransform(388,89.3);

	this.shape_116 = new cjs.Shape();
	this.shape_116.graphics.f("#000000").s().p("AgvBFQgQgdAAgnQAAggAKgYQALgZARgMQANgJAMAAQAXAAASAWQAXAdAAAyQAAAggKAZQgKAYgQAKQgPAMgNAAQgcAAgTgigAgQhTQgLAMgDAaQgEAaAAAYQAAAoAKAaQAIAXAQAAQAHgBAIgGQAJgIAEgRQAHgZAAgsQAAghgHgYQgFgQgJgHQgGgFgIAAQgIAAgIAJg");
	this.shape_116.setTransform(373.1,89.3);

	this.shape_117 = new cjs.Shape();
	this.shape_117.graphics.f("#000000").s().p("AgiBlIAAgGQAOAAAEgCQAEgCACgEQABgDAAgSIAAhpQAAgWgBgGQgBgFgDgCQgCgCgEAAQgGAAgJAEIgDgEIAvgYIAFAAIAACmQAAAQABAFQABAEAFACQAEACAOAAIAAAGg");
	this.shape_117.setTransform(358,89.1);

	this.shape_118 = new cjs.Shape();
	this.shape_118.graphics.f("#000000").s().p("AgwBuQgDgIAEgPQAEgogBiJQAAgMgEgGQgDgFgNgBQgFgCAFgDQAIgCAOAEQAJADAHAFQAHAEAAAFQAAAEgEABQgFABAAAFQgDAeABAiQAOABAVAGQAcAIARALQARAOAAAKQAAAKgIAAQgFAAgIgKQgXgdg1gQIAACAQAAANgGAAQgHAAgFgLg");
	this.shape_118.setTransform(334.7,88.5);

	this.shape_119 = new cjs.Shape();
	this.shape_119.graphics.f("#000000").s().p("AhOBPQBugtAihkQADgHgMgGQgFgCAHgBQALABAHAFQAQALAAAGQAAADgGAAQgGAAgDAIQgvBihrAjQgHAAAFgGgAg9gVQgEgNgEgFQgHgKgPgLQgBAAAAgBQAAAAAAgBQAAAAABAAQAAgBABAAQAJACAMAIQAJAFAGAGQAKAJgBAIQgCAKgFAAQgGAAgDgGgAgJgrQgHgQgGgIQgGgGgNgHQgDgEAEAAQAOACAPAKQAPAMAAAPQAAAHgFABQgGAAgCgGg");
	this.shape_119.setTransform(314.4,93.1);

	this.shape_120 = new cjs.Shape();
	this.shape_120.graphics.f("#000000").s().p("AhMBUIgNgPQAEgCACgFIAAh+QAAgLgEgFQgEgGgMgBQgFgCAFgDQAQgBAOAGQAPAGAAAEQAAADgGAEQgFAEAAAFIAAB/QBVgkBWhJQAFgBgBAFQg2A8hwA9QgDALgEAAQgCAAgHgJg");
	this.shape_120.setTransform(291.1,88.4);

	this.shape_121 = new cjs.Shape();
	this.shape_121.graphics.f("#000000").s().p("AhqB2QBtgnAth/QADgHgGAAQgaAChpANQgEACgGAEQgBAEgEAAQgDAAgMgLQgKgIgBgJQAAgGAFAEQAFAJAPAAICJgLQAOgCAEgIQAOAHAJAJQAGAGAAADQAAAEgIAAQgIAAgBAFQg0CAh0AiQgHAAAEgGgABRhLQgFgHgSgPQgBgBAAAAQAAgBAAAAQAAgBAAAAQABAAABgBQAQAFASAMQAKAHAAAKQAAAJgHAAQgEAAgLgRgABzhaQgFgFgEgHQgJgJgOgIQgDgEAFAAQAbAFAJAJQAHAHAAAIQAAAGgGAAQgFAAgCgCg");
	this.shape_121.setTransform(264.3,87.1);

	this.shape_122 = new cjs.Shape();
	this.shape_122.graphics.f("#000000").s().p("Ag/ByQBpgqgBhWIAAhSQgBgJgEgFQgDgFgMgBQgBgBAAAAQAAgBAAAAQAAAAABgBQAAAAABAAQATgDAPAHQALAFAAADQAAAGgLAGIAABRQABBgh2AnQgIgCAGgFgAgqAUQgEgHABgDIACgSIAAhPQAAgIgEgEQgFgFgJgBQgFgDAFgCQASgBANAHQAKADAAAFQAAAEgEABQgDABAAAJIAABYQABATgJAAQgDAAgEgGg");
	this.shape_122.setTransform(240.3,88.7);

	this.shape_123 = new cjs.Shape();
	this.shape_123.graphics.f("#000000").s().p("AgKBSQgmAohPAKQgHgBAEgFQBOgPAegmQgYgYgTgaIAIgEQAOAVAcAWQAMgTABglIhOAAIAAARQgQAOAAgOIAAhsIASAKIBMAAIAAg4IATADQANAFgTAEIAAAsIBEAAIAIgKIATAMQAKAHgSACIAABQQgPAOAAgMIAAgMIhIAAQAAAsgNAUQA4ApBOAAQgQAKgDALQhFgHg2grgAALAAIBIAAIAAhEIhIAAgAhQAAIBOAAIAAhEIhOAAg");
	this.shape_123.setTransform(217,88.1);

	this.shape_124 = new cjs.Shape();
	this.shape_124.graphics.f("#000000").s().p("AhyCAQBIgbAAgwIAAgsQgoAqgwAUQgKABAHgHQBBgiApg8IgqAAIAAAUQgPAMAAgLIAAh8IASAMICEAAIAHgJIARAMQAHAGgMACIAABeQgPAPAAgNIAAgQIg2AAQAwAyBJANQgOAGgHANQgmgQgbgUIgHADIAABpQgPAOAAgOIAAh3IAOADQgWgSgOgUIgOAAQgQAXgPAMIAQACQAKAGgPADIAAAjQAAA6hWAXQgGgBAFgEgAAHgkIA/AAIAAgiIg/AAgAhFgkIA+AAIAAgiIg+AAgAAHhNIA/AAIAAgkIg/AAgAhFhNIA+AAIAAgkIg+AAg");
	this.shape_124.setTransform(187,88.7);

	this.shape_125 = new cjs.Shape();
	this.shape_125.graphics.f("#000000").s().p("AhTB8IAAiiIg1AAIAAgHIA1AAIAAhNIAUAEQAKAGgOACIAABBIA2AAIAAhUIASAEQAKAGgOACIAABIIAyAAIAAhSIAUADQAKAGgOACIAABHIAaAAIASgSIAWAQQAHAGgHADIhCAAIAABfQgQAOAAgNIAAgSIgyAAIAAAbQgNAOgBgMIAAhrIg2AAIAACHICZAAIASgSIAWARQAHAFgHADIjBAAIAAATQgJAHgDAAQgEAAAAgGgAABAhIAyAAIAAhHIgyAAg");
	this.shape_125.setTransform(157.1,88.8);

	this.shape_126 = new cjs.Shape();
	this.shape_126.graphics.f("#000000").s().p("AADBuQgTgVgMgdQgLgdAAgfQAAgsAWglQAVglAkgRIAAAHQgSAKgMARQgKARgFAbQgGAaAAAdQAAAdAFAaQAEAUADANQAGAMAJALQAJALAPAKIAAAGQgWgLgPgPg");
	this.shape_126.setTransform(137,92);

	this.shape_127 = new cjs.Shape();
	this.shape_127.graphics.f("#000000").s().p("Ag4CIIAAgyIA/AAIAAjdIAzAAIAAEPgAguB+IBdAAIAAj7IgeAAIAADeIg/AAg");
	this.shape_127.setTransform(428.3,53.4);

	this.shape_128 = new cjs.Shape();
	this.shape_128.graphics.f("#000000").s().p("AiFB4QA+gjAZguQAcgzADhJIAAgnIAWADQANAFgTAFIAAAPQAPCWB4AuQgRAAgQAOQhZg4gQiHQgDBPgeAvQgdAuhDAeIgCAAQgEAAAEgFg");
	this.shape_128.setTransform(406,53.8);

	this.shape_129 = new cjs.Shape();
	this.shape_129.graphics.f("#000000").s().p("AAIB+QAsgjASgeQgNgigBgwIhlAAIAAgHIA1AAIAQg2IAPAGQALAGgQACIgUAoIAqAAIAAhjIAVADQAMADgSAHIAABWIAbAAIAPgPIATAOQAHAGgHACIg9AAQABAqAIAYQANgZALgcIAQAIQANADgTAFQgMAcgQAZQAKASAIAJQAIAIAEAAQADAAABgGIAHghQAEgGACAHIgDAlQAAAJAGADQAEADAAADQAAAHgOAAQgOAAgPgPQgMgMgJgUQgaAigoAYIgCAAQgEAAAEgFgAh5B4IAAhrIARAJIAbAAIAHgJIARALQAHAGgMACIAABKQgPAOAAgNIAAgKIghAAIAAAWQgIAHgEAAQgDAAAAgGgAhqBaIAhAAIAAg9IghAAgAggBmIAAhqIARAHIAgAAIAHgHIARAJQAHAGgMADIAABMQgPAOAAgNIAAgFIgmAAIAAAOQgIAHgEAAQgDAAAAgFgAgRBPIAmAAIAAgfIgmAAgAgRApIAmAAIAAgfIgmAAgAiCgHIAAgHIAzAAIALgLIARANQADAEgFABgAgWgxQgBgRgJgQQgDgFAGADQAWAVAAATQAAAKgIAAQgIAAABgPgAiAgmIAAgHIAtAAIAMgMIAQANQAEAFgGABgABqhJQgHgNgOgKQgFgEAJABQAlANgCAPQgBAHgGAAQgGAAgFgJgAiLhGIAAgHIBDAAIAPgPIATAOQAHAGgHACgAgmhXIAAgHIAhAAIAAgkIARAEQAKADgOAFIAAAYIAMAAIAMgNIARALQAHAGgHADgAh/hmIAAgHIArAAIANgMIAQALQAHAGgHACg");
	this.shape_129.setTransform(375.7,53.3);

	this.shape_130 = new cjs.Shape();
	this.shape_130.graphics.f("#000000").s().p("AiBB+QBIg0AChFIhIAAIAAgFIBJAAIAAg6IgdAAQgPAYgMALQgEABABgEQAbgpAOg9IAYAJQAGAHgQABIgVAuIA+AAIANgMIAOALQAHAGgHACIgwAAIAAA6IAfAAIAOgPIASANQAHAFgHACIhAAAQgCAVgHAUQAcAOAUAUQAKAMAAAJQAAALgGAAQgHAAgFgMQgIgXgigaQgWAzg3AbQgFAAADgDgAAjBvIAAi7IARAKIA1AAIAHgJIAQALQAIAHgMACIAACXQgPAOAAgMIAAgRIg7AAIAAAcQgIAHgEAAQgDAAAAgFgAAyBKIA7AAIAAiFIg7AAg");
	this.shape_130.setTransform(345.3,52.8);

	this.shape_131 = new cjs.Shape();
	this.shape_131.graphics.f("#000000").s().p("Ah5B9IAAkAIARAMIDEAAIAIgKIATAMQAKAHgSADIAADiQgPAOAAgMIAAgMIjKAAIAAAPQgIAIgEAAQgDAAAAgHgAhqBmIDKAAIAAjWIjKAAgAhVBAIAAgHIBDAAIAAhCIg1AAIAAgHIA1AAIAAg2IhBAAIAAgHIB+AAIANgNIAQAMQAHAGgHACIhLAAIAAA2IAlAAIALgLIARAMQADAFgGABIg+AAIAABCIA2AAIAPgPIATAOQAHAGgHACgAAiAkQgLgRgNgJQgDgDAGAAQAjAJAAASQAAAJgGAAQgFAAgDgHg");
	this.shape_131.setTransform(316.4,53.8);

	this.shape_132 = new cjs.Shape();
	this.shape_132.graphics.f("#000000").s().p("AgNB+IAAhqIhSAAIAAANQgQAOAAgNIAAh5IASAKIBQAAIAAg3IATAEQANAEgTAFIAAAqIBSAAIAIgKIATANQAJAHgRACIAABfQgQAOAAgNIAAgLIhVAAIAABpQgGAIgEAAQgDAAAAgHgAAAANIBVAAIAAhTIhVAAgAhfANIBSAAIAAhTIhSAAg");
	this.shape_132.setTransform(286.5,53.4);

	this.shape_133 = new cjs.Shape();
	this.shape_133.graphics.f("#000000").s().p("AhFBlQgNgNAAgQQABgTASgSQATgRAcgQQgOgOAAgeQAAg2gCgGQgFgMgMAAQgEgCAEgDQAUgCAQANQAGAFgFAEQgDAEAAAKIAAA9QAAAUAGAEQAfgNAjgLQAKgCgHgJQgCgEgGgDQgEgDAGgBQANABAIAKQAHAKABAHQgBAGgIAAQg0ALgjAPQggAPgRASQgLAMAAALQAAAZAeAIQANAEAkAAQAjAAAOgFQAMgFAHAFQAEAEAAAEQAAAFgHABQgVAEg3AAQgtAAgTgTg");
	this.shape_133.setTransform(260.6,52.9);

	this.shape_134 = new cjs.Shape();
	this.shape_134.graphics.f("#000000").s().p("ABVB8QgEgIgKgOIieAQQgHAWgGgOIgLgWIA1gBIAYhDIhgAAIAAgHIDYAAIAPgPIATAOQAHAGgHACIiGAAIgjBCIBzgGQgPgQgTgOQgGgEAIABQAfAMAWASQAQAOAAAQQAAALgIAAQgGAAgEgKgAiFgLQBOgtAvhNIAXAKQAGAKgRgEQAsA6BXAfQgOAFgHAMQhNgoglg/QhCBUhBAXQgGAAAEgEgAhKgRIAAgHIBoAAIAMgNIARAMQAHAGgHACg");
	this.shape_134.setTransform(234.6,53);

	this.shape_135 = new cjs.Shape();
	this.shape_135.graphics.f("#000000").s().p("AhsBVQBwg8AxhdQACgEgGAAQhWAMgFAHQgCADgEAAQgCAAgIgHQgSgPACgIQAAgGAFAEQAGALAMAAQAcAABLgJIALgJQAJAGAIAHQAFAEAAAEQAAAEgLAAQgWAjgYAdQAnALAZAZQAUAUAAAMQAAAKgJAAQgFAAgHgMQgLgRgOgOQgQgRgagQQg5A7hHAdIgEAAQgFAAAFgFg");
	this.shape_135.setTransform(206.8,53.3);

	this.shape_136 = new cjs.Shape();
	this.shape_136.graphics.f("#000000").s().p("AiABrQByg8AvhdQACgEgGAAQhWAMgFAHQgCADgEAAQgCAAgIgHQgSgPACgIQAAgGAFAEQAGALAMAAQAcAABLgJIALgJQAJAGAIAHQAFAEAAAEQAAAEgLAAQgWAjgYAbQAnANAZAZQAUAUAAAMQAAAKgJAAQgFAAgHgMQgLgRgOgOQgQgRgagQQg5A7hHAdIgEAAQgFAAAFgFgABPhEQgFgHgSgPQgBgBAAAAQAAgBAAAAQAAAAAAgBQABAAABgBQAQAFASAMQAKAHAAAKQAAAJgHAAQgEAAgLgRgAB3hOIgJgMQgJgJgOgJQgDgDAEAAQAbAFAKAJQAHAHAAAIQAAAGgGAAQgFAAgCgCg");
	this.shape_136.setTransform(181.8,51.1);

	this.shape_137 = new cjs.Shape();
	this.shape_137.graphics.f("#000000").s().p("AhxA9QgJgJgEgJQAAgIAFAFQAIAJANAAQAcABBHgHIAAg9QAAgKgDgHQgDgHgLgGQgvAGgEACQgGAEgEAAQgCAAgKgIQgKgKAAgHQABgHACAEQAHALAQAAIAXAAQA0gFA5gDIAQgHQAJAEAHAGQAGAEAAAEQAAAEgHgCQgggGg9AFIAQAJQAIAFAAADQAAAGgHABIgDBDIBJgCQALgBAHgFQAIACAJAHQAKAHAAAFQAAAEgJgCQgUgFgSABQhMgHhSAQQgKABgEACQgCAEgGAAQgDgBgKgHg");
	this.shape_137.setTransform(153.9,53.5);

	this.shape_138 = new cjs.Shape();
	this.shape_138.graphics.f("#000000").s().p("AAYBzQgHgJACgIQAEgNAAgIIAAhlQhDAyg5AVQgJAAAHgFQB3hAA6hLQAFgGgBgFQgBgEgKgFQgHgCAKgCQASACAKANQAJAIAAAEQAAAGgHgCQgGAAgGAFQgVAYghAaQAaAIgWAFIAACFQAAALgFgBQgDAAgGgGg");
	this.shape_138.setTransform(127.8,53.5);

	this.shape_139 = new cjs.Shape();
	this.shape_139.graphics.f("#000000").s().p("Ag5CJIAAkRIByAAIAAAzIg/AAIAADegAguB+IAeAAIAAjeIA/AAIAAgdIhdAAg");
	this.shape_139.setTransform(109,53);

	this.shape_140 = new cjs.Shape();
	this.shape_140.graphics.f("#000000").s().p("AhxB1QgBgPAKgHQALgHAOgNQBGhBAkgjQAJgKgNADQgiAGggAKQgKAEgRAJQgIADgIgGQgLgLAEgTQAEgJAAAJQACAKADADQAEAEAHAAQAJAAAMgEQAogMAqgFIAGgFQAEgCAEACQALAGADADQAGAHgIABQgJACgEADIhOBHQAJgDAKAAQAOAAAFAHQAHAIABAOQADAYADAGQAFAHAXAAQAnAAAJgFQAKgEAIAJQAIAMgLAAIhDAAQggAAgHgSQgCgGgBgcQgBgRgTAAQgRAAgOAOQgoAogHAJQgEAFgEABIgCAAQgEAAAAgGgAgmhJQAOgHATgEQgcgJgLgbQAAgBAAAAQABgBAAAAQAAAAABAAQABAAABABQALAUAfAEQAPADAFAKQAHAPgPgEQgTgGggAJIgBABQgBAAAAgBQgBAAAAAAQAAgBABAAQAAgBABgBg");
	this.shape_140.setTransform(310.4,17.1);

	this.shape_141 = new cjs.Shape();
	this.shape_141.graphics.f("#000000").s().p("AghB4QgcgHgOgPQgNgOAAgQQAAgUAMgKQAUgSAoAAQAQAAAOACQAZADAMAEQAHACgFgHQgZgggWgiQggAHgYADIgLACQgGgBgFgEQgOgNgCgFQgCgGAGAEQALAKAUAAQAVABAggJIgSgfQgEgHgGgFQgHgGAHgHQAMgMAMgEQAHAAgDAEQgHADgCAMQgCAHAGAKQAKAVAIAMQAVgFAfgOQAGgDAJACQAFABADADQAEAEgHAEQgRAHgxALQAMAVAVAZQANASAHAHQAEAFAHAEQAEADABAFQACAJgBACQgEAJgJgFQgSgOgXgIQgdgIgTgBQgnAAgQAQQgJAKAAAKQAAAUAMAKQAWARAqACQAhABAJgEQAKgDAGADQAFAEADAEQACAHgHAAQgOADgaAAQgdAAgYgGg");
	this.shape_141.setTransform(285,17.4);

	this.shape_142 = new cjs.Shape();
	this.shape_142.graphics.f("#000000").s().p("Ah2B9IAAj/IATALIC/AAIAHgKIARAMQAHAGgMACIAADPQAAANgIAIQgHAHgHAAQgHAAAAgGQAAgHgFgBIgWgFQgGgCAGgCIAeAAQALAAAAgLIAAjMIjHAAIAADsQgHAHgEAAQgEAAAAgGgAhBBVIAAhjIAUAEQAJAGgOACIAABBIAlAAIAAhcIhEAAIAAgHIBaAAIAUhEIAVAMQAHAGgQABIgZAxIAfAAIAPgPIATAOQAHAGgHACIhRAAIAABcIAmAAIAAhMIAUAEQAKAGgOACIAABRQgQAOAAgNIAAgLIhYAAIAAAOQgIAHgEAAQgDAAAAgGgAgsg+QgCgRgQgQQgCgEAGACQAgAPAAAXQAAAMgHAAQgJAAgCgPg");
	this.shape_142.setTransform(259.2,18.3);

	this.shape_143 = new cjs.Shape();
	this.shape_143.graphics.f("#000000").s().p("AgtBvIAAh0QgrAngrAUQgHABAFgGQBXg0AphbIhyAAIAAgHIDZAAIAQgQIASAPQAHAFgHADIh2AAQgUAsgbAfIAHAGIBlAAIAHgKIAQAMQAHAGgLACIAABoQgQAOAAgNIAAgTIhsAAIAAAbQgIAIgDAAQgEAAAAgHgAgeBMIBsAAIAAhSIhsAAg");
	this.shape_143.setTransform(228.6,18.5);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_143},{t:this.shape_142},{t:this.shape_141},{t:this.shape_140},{t:this.shape_139},{t:this.shape_138},{t:this.shape_137},{t:this.shape_136},{t:this.shape_135},{t:this.shape_134},{t:this.shape_133},{t:this.shape_132},{t:this.shape_131},{t:this.shape_130},{t:this.shape_129},{t:this.shape_128},{t:this.shape_127},{t:this.shape_126},{t:this.shape_125},{t:this.shape_124},{t:this.shape_123},{t:this.shape_122},{t:this.shape_121},{t:this.shape_120},{t:this.shape_119},{t:this.shape_118},{t:this.shape_117},{t:this.shape_116},{t:this.shape_115},{t:this.shape_114},{t:this.shape_113},{t:this.shape_112},{t:this.shape_111},{t:this.shape_110},{t:this.shape_109},{t:this.shape_108},{t:this.shape_107},{t:this.shape_106},{t:this.shape_105},{t:this.shape_104},{t:this.shape_103},{t:this.shape_102},{t:this.shape_101},{t:this.shape_100},{t:this.shape_99},{t:this.shape_98},{t:this.shape_97},{t:this.shape_96},{t:this.shape_95},{t:this.shape_94},{t:this.shape_93},{t:this.shape_92},{t:this.shape_91},{t:this.shape_90},{t:this.shape_89},{t:this.shape_88},{t:this.shape_87},{t:this.shape_86},{t:this.shape_85},{t:this.shape_84},{t:this.shape_83},{t:this.shape_82},{t:this.shape_81},{t:this.shape_80},{t:this.shape_79},{t:this.shape_78},{t:this.shape_77},{t:this.shape_76},{t:this.shape_75},{t:this.shape_74},{t:this.shape_73},{t:this.shape_72},{t:this.shape_71},{t:this.shape_70},{t:this.shape_69},{t:this.shape_68},{t:this.shape_67},{t:this.shape_66},{t:this.shape_65},{t:this.shape_64},{t:this.shape_63},{t:this.shape_62},{t:this.shape_61},{t:this.shape_60},{t:this.shape_59},{t:this.shape_58},{t:this.shape_57},{t:this.shape_56},{t:this.shape_55},{t:this.shape_54},{t:this.shape_53},{t:this.shape_52},{t:this.shape_51},{t:this.shape_50},{t:this.shape_49},{t:this.shape_48},{t:this.shape_47},{t:this.shape_46},{t:this.shape_45},{t:this.shape_44},{t:this.shape_43},{t:this.shape_42},{t:this.shape_41},{t:this.shape_40},{t:this.shape_39},{t:this.shape_38},{t:this.shape_37},{t:this.shape_36},{t:this.shape_35},{t:this.shape_34},{t:this.shape_33},{t:this.shape_32},{t:this.shape_31},{t:this.shape_30},{t:this.shape_29},{t:this.shape_28},{t:this.shape_27},{t:this.shape_26},{t:this.shape_25},{t:this.shape_24},{t:this.shape_23},{t:this.shape_22},{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,537.3,566);


(lib.bg = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// レイヤー 1
	this.instance = new lib.timessquare001();
	this.instance.setTransform(0,0,2,1.5);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,1920,1080);


// stage content:
(lib.TextTest = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// test_v004_front.png
	this.instance = new lib.トゥイーン1("synched",0);
	this.instance.setTransform(2880.9,540);
	this.instance._off = true;

	this.instance_1 = new lib.トゥイーン2("synched",0);
	this.instance_1.setTransform(960,540);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[]}).to({state:[{t:this.instance}]},61).to({state:[{t:this.instance_1}]},17).wait(27));
	this.timeline.addTween(cjs.Tween.get(this.instance).wait(61).to({_off:false},0).to({_off:true,x:960},17).wait(27));

	// Text
	this.instance_2 = new lib.Text();
	this.instance_2.setTransform(1156.8,1353.9,1,1,0,0,0,268.6,283);

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(1).to({regX:268.3,regY:266.7,x:1156.5,y:1327.4},0).wait(1).to({y:1317.3},0).wait(1).to({y:1307.1},0).wait(1).to({y:1297},0).wait(1).to({y:1286.8},0).wait(1).to({y:1276.7},0).wait(1).to({y:1266.5},0).wait(1).to({y:1256.4},0).wait(1).to({y:1246.2},0).wait(1).to({y:1236.1},0).wait(1).to({y:1225.9},0).wait(1).to({y:1215.8},0).wait(1).to({y:1205.6},0).wait(1).to({y:1195.5},0).wait(1).to({y:1185.3},0).wait(1).to({y:1175.2},0).wait(1).to({y:1165},0).wait(1).to({y:1154.9},0).wait(1).to({y:1144.7},0).wait(1).to({y:1134.6},0).wait(1).to({y:1124.4},0).wait(1).to({y:1114.3},0).wait(1).to({y:1104.1},0).wait(1).to({y:1094},0).wait(1).to({y:1083.8},0).wait(1).to({y:1073.7},0).wait(1).to({y:1063.5},0).wait(1).to({y:1053.4},0).wait(1).to({y:1043.2},0).wait(1).to({y:1033.1},0).wait(1).to({y:1022.9},0).wait(1).to({y:1012.8},0).wait(1).to({y:1002.6},0).wait(1).to({y:992.5},0).wait(1).to({y:982.3},0).wait(1).to({y:972.2},0).wait(1).to({y:962},0).wait(1).to({y:951.9},0).wait(1).to({y:941.7},0).wait(1).to({y:931.6},0).wait(1).to({y:921.4},0).wait(1).to({y:911.3},0).wait(1).to({y:901.1},0).wait(1).to({y:891},0).wait(1).to({y:880.8},0).wait(1).to({y:870.7},0).wait(1).to({y:860.5},0).wait(1).to({y:850.4},0).wait(1).to({y:840.2},0).wait(1).to({y:830.1},0).wait(1).to({y:819.9},0).wait(1).to({y:809.8},0).wait(1).to({y:799.6},0).wait(1).to({y:789.5},0).wait(1).to({y:779.3},0).wait(1).to({y:769.2},0).wait(1).to({y:759},0).wait(1).to({y:748.9},0).wait(1).to({y:738.7},0).wait(1).to({y:728.6},0).wait(1).to({y:718.4},0).wait(1).to({y:708.3},0).wait(1).to({y:698.1},0).wait(1).to({y:688},0).wait(1).to({y:677.8},0).wait(1).to({y:667.7},0).wait(1).to({y:657.5},0).wait(1).to({y:647.4},0).wait(1).to({y:637.2},0).wait(1).to({y:627.1},0).wait(1).to({y:616.9},0).wait(1).to({y:606.8},0).wait(1).to({y:596.6},0).wait(1).to({y:586.5},0).wait(1).to({y:576.3},0).wait(1).to({y:566.2},0).wait(1).to({y:556},0).wait(1).to({y:545.9},0).wait(1).to({y:535.7},0).wait(1).to({y:525.6},0).wait(1).to({y:515.4},0).wait(1).to({y:505.3},0).wait(1).to({y:495.1},0).wait(1).to({y:485},0).wait(1).to({y:474.8},0).wait(1).to({y:464.7},0).wait(1).to({y:454.5},0).wait(1).to({y:444.4},0).wait(1).to({y:434.2},0).wait(1).to({y:424.1},0).wait(1).to({y:413.9},0).wait(1).to({y:403.8},0).wait(1).to({y:393.6},0).wait(1).to({y:383.5},0).wait(1).to({y:373.3},0).wait(1).to({y:363.2},0).wait(1).to({y:353.1},0).wait(1).to({y:342.9},0).wait(1).to({y:332.8},0).wait(1).to({y:322.6},0).wait(1).to({y:312.4},0).wait(1).to({y:302.3},0).wait(1).to({y:292.1},0).wait(1).to({y:282},0).wait(1));

	// レイヤー 7
	this.instance_3 = new lib.screen();

	this.timeline.addTween(cjs.Tween.get(this.instance_3).wait(105));

	// レイヤー 6
	this.instance_4 = new lib.bg();
	this.instance_4.setTransform(-976.8,540,1,1,0,0,0,960,540);
	this.instance_4._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_4).wait(61).to({_off:false},0).to({x:960},17).wait(27));

	// test_v004_back.png
	this.instance_5 = new lib.test_v004_back();

	this.timeline.addTween(cjs.Tween.get(this.instance_5).wait(105));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(960,540,1920,1636.9);

})(lib = lib||{}, images = images||{}, createjs = createjs||{}, ss = ss||{});
var lib, images, createjs, ss;